// Comprehensive STRAND profile PDF — exports EVERY data point the app holds for
// the signed-in user. Renders a multi-section branded A4 PDF that can be
// downloaded or shared (via Web Share API / email).
//
// Sections (in order):
//   1.  Cover
//   2.  Basic details + water hardness
//   3.  Hair profile
//   4.  Style & colour
//   5.  Health & lifestyle
//   6.  Medications
//   7.  Blood markers (full panel)
//   8.  AI summaries
//   9.  Goals + updates
//  10.  Professional / clinician
//  11.  Appointments
//  12.  On-shelf products
//  13.  Wishlist products
//  14.  Off-shelf products
//  15.  Favourites
//  16.  Tools
//  17.  Wash days (full log)
//  18.  Style journal entries
//  19.  Moodboards
//  20.  Flagged ingredients

import { jsPDF } from "jspdf";
import { supabase } from "@/integrations/supabase/client";
import { loadClinicalContext } from "@/lib/clinicalContext";
import { getWaterHardness } from "@/data/hardWaterPostcodes";
import { BLOOD_RANGES, evaluate, statusLabel } from "@/data/bloodRanges";

const PAGE = { w: 210, h: 297 };
const MARGIN = 16;
const CONTENT_W = PAGE.w - MARGIN * 2;

const COLORS = {
  background: [242, 232, 217] as [number, number, number],
  card: [253, 248, 242] as [number, number, number],
  border: [221, 208, 184] as [number, number, number],
  charcoal: [44, 36, 22] as [number, number, number],
  muted: [122, 106, 84] as [number, number, number],
  gold: [196, 154, 60] as [number, number, number],
  warn: [184, 112, 32] as [number, number, number],
  good: [90, 138, 90] as [number, number, number],
};

type RGB = [number, number, number];

const fmtDate = (iso?: string | null): string => {
  if (!iso) return "";
  try {
    return new Date(iso).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" });
  } catch { return iso; }
};

const toText = (v: unknown): string => {
  if (Array.isArray(v)) return v.filter(Boolean).join(", ");
  if (v === null || v === undefined) return "";
  if (typeof v === "object") return JSON.stringify(v);
  return String(v);
};

// ─── Layout primitives ────────────────────────────────────────────────────

function paintBackground(doc: jsPDF) {
  doc.setFillColor(...COLORS.background);
  doc.rect(0, 0, PAGE.w, PAGE.h, "F");
}

function drawHeader(doc: jsPDF, subtitle: string) {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(22);
  doc.setTextColor(...COLORS.charcoal);
  doc.text("STRAND", MARGIN, 20, { charSpace: 1.2 });
  doc.setFontSize(7.5);
  doc.setTextColor(...COLORS.gold);
  doc.text("FULL PROFILE EXPORT", PAGE.w - MARGIN, 20, { align: "right", charSpace: 0.5 });
  doc.setDrawColor(...COLORS.gold);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, 24, PAGE.w - MARGIN, 24);
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  doc.text(subtitle, MARGIN, 30);
}

function drawFooter(doc: jsPDF, page: number, total: number) {
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.15);
  doc.line(MARGIN, PAGE.h - 14, PAGE.w - MARGIN, PAGE.h - 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...COLORS.muted);
  doc.text("Generated by STRAND · Confidential — for personal use", MARGIN, PAGE.h - 9);
  doc.text(`Page ${page} of ${total}`, PAGE.w - MARGIN, PAGE.h - 9, { align: "right" });
}

class Cursor {
  y: number;
  constructor(public doc: jsPDF, public subtitle: string) { this.y = 36; }

  ensure(needed: number) {
    if (this.y + needed <= PAGE.h - 18) return;
    this.doc.addPage();
    paintBackground(this.doc);
    drawHeader(this.doc, this.subtitle);
    this.y = 36;
  }

  section(label: string, tone: RGB = COLORS.gold) {
    this.ensure(14);
    this.y += 4;
    this.doc.setFont("helvetica", "normal");
    this.doc.setFontSize(8);
    this.doc.setTextColor(...tone);
    this.doc.text(label.toUpperCase(), MARGIN, this.y, { charSpace: 0.5 });
    this.doc.setDrawColor(...tone);
    this.doc.setLineWidth(0.25);
    this.doc.line(MARGIN, this.y + 1.4, MARGIN + 16, this.y + 1.4);
    this.y += 6;
  }

  row(label: string, value: string, tone: RGB = COLORS.charcoal) {
    if (!value) return;
    const lines = this.doc.splitTextToSize(value, CONTENT_W - 42);
    const h = Math.max(11, 6 + lines.length * 4);
    this.ensure(h + 2);
    this.doc.setFillColor(...COLORS.card);
    this.doc.setDrawColor(...COLORS.border);
    this.doc.setLineWidth(0.12);
    this.doc.roundedRect(MARGIN, this.y, CONTENT_W, h, 1.2, 1.2, "FD");
    this.doc.setFont("helvetica", "normal");
    this.doc.setFontSize(7.5);
    this.doc.setTextColor(...COLORS.muted);
    this.doc.text(label, MARGIN + 4, this.y + 4.5);
    this.doc.setFontSize(9);
    this.doc.setTextColor(...tone);
    this.doc.text(lines, MARGIN + 34, this.y + 4.5);
    this.y += h + 2;
  }

  paragraph(text: string, tone: RGB = COLORS.charcoal, size = 9) {
    if (!text) return;
    const lines = this.doc.splitTextToSize(text, CONTENT_W - 6);
    const h = 3 + lines.length * (size * 0.42);
    this.ensure(h + 2);
    this.doc.setFont("helvetica", "normal");
    this.doc.setFontSize(size);
    this.doc.setTextColor(...tone);
    this.doc.text(lines, MARGIN + 2, this.y + 3);
    this.y += h + 2;
  }

  card(title: string, lines: { label?: string; value: string; tone?: RGB }[], tone: RGB = COLORS.charcoal) {
    const valid = lines.filter(l => l.value);
    if (valid.length === 0) return;
    const wrapped = valid.map(l => ({
      ...l,
      wrapped: this.doc.splitTextToSize(l.label ? `${l.label}: ${l.value}` : l.value, CONTENT_W - 8),
    }));
    const h = 8 + wrapped.reduce((s, l) => s + l.wrapped.length * 4, 0) + 2;
    this.ensure(h + 2);
    this.doc.setFillColor(...COLORS.card);
    this.doc.setDrawColor(...COLORS.border);
    this.doc.setLineWidth(0.12);
    this.doc.roundedRect(MARGIN, this.y, CONTENT_W, h, 1.5, 1.5, "FD");
    this.doc.setFont("helvetica", "bold");
    this.doc.setFontSize(9.5);
    this.doc.setTextColor(...tone);
    this.doc.text(title, MARGIN + 4, this.y + 5);
    let yy = this.y + 9.5;
    this.doc.setFont("helvetica", "normal");
    this.doc.setFontSize(8.5);
    for (const l of wrapped) {
      this.doc.setTextColor(...(l.tone ?? COLORS.charcoal));
      this.doc.text(l.wrapped, MARGIN + 4, yy);
      yy += l.wrapped.length * 4;
    }
    this.y += h + 2;
  }

  empty(text: string) {
    this.paragraph(text, COLORS.muted, 8.5);
  }
}

// ─── Data fetch ───────────────────────────────────────────────────────────

async function fetchAll(userId: string) {
  const [
    profile, clinical, blood, summaries, goals, goalUpdates, products, tools,
    washes, journal, boards, boardImages, appts, ingLists, meds, photos, ratings,
  ] = await Promise.all([
    supabase.from("profiles").select("display_name, postcode, country, heritage, birth_year").eq("user_id", userId).maybeSingle(),
    loadClinicalContext(),
    supabase.from("blood_results").select("marker, value, unit, status, category").eq("user_id", userId),
    supabase.from("ai_summaries").select("kind, payload, updated_at").eq("user_id", userId),
    supabase.from("user_goals").select("*").eq("user_id", userId).order("created_at", { ascending: false }),
    supabase.from("goal_updates").select("*").eq("user_id", userId).order("created_at", { ascending: false }),
    supabase.from("user_products").select("name, brand, category, rating, match_score, on_shelf, on_wishlist, on_favourite, previously_on_shelf, off_shelf_reason, use_count, last_used_at, added_to_shelf_at, ai_summary, ingredients, key_ingredients, source_url").eq("user_id", userId),
    supabase.from("user_tools").select("name, brand, category, rating, on_shelf, on_favourite, use_count, last_used_at, notes, source_url").eq("user_id", userId),
    supabase.from("wash_days").select("wash_date, steps, scalp_feel, breakage, hair_feel_note, style_after, stress_level, duration_min, ai_insight, heat_treatment, product_ids").eq("user_id", userId).order("wash_date", { ascending: false }),
    supabase.from("journal_entries").select("entry_date, title, note, mood, products_used, photo_paths").eq("user_id", userId).order("entry_date", { ascending: false }),
    supabase.from("moodboards").select("id, name, emoji, gradient, is_favourites, created_at").eq("user_id", userId),
    supabase.from("moodboard_images").select("board_id, caption, is_favourite, created_at").eq("user_id", userId),
    supabase.from("appointments").select("appointment_date, appointment_time, professional_name, professional_type, clinic_name, reason, notes, status, follow_up_needed").eq("user_id", userId).order("appointment_date", { ascending: false }),
    supabase.from("ingredient_lists").select("ingredient, list_kind, reason, product_count").eq("user_id", userId),
    supabase.from("user_medications").select("name, category").eq("user_id", userId),
    supabase.from("user_product_photos").select("product_key, kind, created_at").eq("user_id", userId),
    supabase.from("product_ratings").select("product_name, product_brand, rating, created_at").eq("user_id", userId),
  ]);

  return {
    profile: profile.data,
    clinical,
    blood: blood.data ?? [],
    summaries: summaries.data ?? [],
    goals: goals.data ?? [],
    goalUpdates: goalUpdates.data ?? [],
    products: products.data ?? [],
    tools: tools.data ?? [],
    washes: washes.data ?? [],
    journal: journal.data ?? [],
    boards: boards.data ?? [],
    boardImages: boardImages.data ?? [],
    appts: appts.data ?? [],
    ingLists: ingLists.data ?? [],
    meds: meds.data ?? [],
    photos: photos.data ?? [],
    ratings: ratings.data ?? [],
  };
}

// ─── Generator ────────────────────────────────────────────────────────────

export async function generateFullProfilePdf(): Promise<{ blob: Blob; fileName: string }> {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error("Not signed in");

  const d = await fetchAll(user.id);

  const displayName =
    d.clinical.basic?.name?.trim() ||
    d.profile?.display_name?.trim() ||
    (user.user_metadata?.display_name as string | undefined)?.trim() ||
    (user.email ? user.email.split("@")[0] : "STRAND Member");

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  paintBackground(doc);

  // ── Cover ──
  doc.setFont("helvetica", "normal");
  doc.setFontSize(36);
  doc.setTextColor(...COLORS.charcoal);
  doc.text("STRAND", MARGIN, 60, { charSpace: 1.6 });
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.gold);
  doc.text("FULL PROFILE EXPORT", MARGIN, 68, { charSpace: 0.5 });
  doc.setDrawColor(...COLORS.gold);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, 74, MARGIN + 40, 74);

  doc.setFontSize(20);
  doc.setTextColor(...COLORS.charcoal);
  doc.text(displayName, MARGIN, 92);
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.muted);
  doc.text(`Generated ${new Date().toLocaleDateString(undefined, { day: "numeric", month: "long", year: "numeric" })}`, MARGIN, 100);
  if (user.email) doc.text(user.email, MARGIN, 106);

  // Summary counts on cover
  const counts: [string, number][] = [
    ["Blood markers", d.blood.length],
    ["Goals", d.goals.length],
    ["Products", d.products.length],
    ["Tools", d.tools.length],
    ["Wash days", d.washes.length],
    ["Journal entries", d.journal.length],
    ["Moodboards", d.boards.length],
    ["Appointments", d.appts.length],
  ];
  let cy = 130;
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.gold);
  doc.text("WHAT'S INCLUDED", MARGIN, cy);
  cy += 6;
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.charcoal);
  for (const [label, n] of counts) {
    doc.setTextColor(...COLORS.muted);
    doc.text(label, MARGIN, cy);
    doc.setTextColor(...COLORS.charcoal);
    doc.text(String(n), MARGIN + 70, cy);
    cy += 6;
  }

  drawFooter(doc, 1, 1); // placeholder
  doc.addPage();
  paintBackground(doc);
  const subtitle = `${displayName} · ${new Date().toLocaleDateString()}`;
  drawHeader(doc, subtitle);
  const cur = new Cursor(doc, subtitle);

  // ── Basic details ──
  cur.section("Basic details");
  cur.row("Name", displayName);
  if (user.email) cur.row("Email", user.email);
  const basic = d.clinical.basic;
  if (basic?.age) cur.row("Age", String(basic.age));
  if (basic?.birth_year) cur.row("Birth year", String(basic.birth_year));
  if (basic?.postcode) cur.row("Postcode", basic.postcode);
  if (basic?.country) cur.row("Country", basic.country);
  if (basic?.heritage?.length) cur.row("Heritage", basic.heritage.join(", "));
  const hardness = basic?.postcode ? getWaterHardness(basic.postcode) : null;
  if (hardness) cur.row("Water", hardness === "hard" ? "Hard water area" : "Soft water area", hardness === "hard" ? COLORS.warn : COLORS.good);

  // ── Hair profile ──
  cur.section("Hair profile");
  const hair = d.clinical.hair;
  if (!hair) cur.empty("No hair profile recorded yet.");
  else {
    cur.row("Strand diameter", toText(hair.diameter));
    cur.row("Surface texture", toText(hair.texture));
    cur.row("Density", toText(hair.density));
    cur.row("Porosity", toText(hair.porosity));
    cur.row("Elasticity", toText(hair.elasticity));
    cur.row("Scalp", toText(hair.scalp));
    cur.row("Diagnosed conditions", toText(hair.diagnosed), COLORS.warn);
    cur.row("Areas of concern", toText(hair.areas));
  }

  // ── Style & colour ──
  cur.section("Style & colour");
  const style = d.clinical.style;
  if (!style) cur.empty("No style profile recorded yet.");
  else {
    cur.row("Current hairstyle", toText(style.current_hairstyle));
    cur.row("Style set on", fmtDate(style.style_set_at));
    cur.row("How long in style", toText(style.howLong));
    cur.row("Planned next style", toText(style.planned_next_style));
    cur.row("Planned change date", fmtDate(style.planned_change_date));
    cur.row("Default styles", toText(style.default_styles));
    cur.row("Current colour status", toText(style.colour));
    cur.row("Chemical history", toText(style.chemical_history));
  }

  // ── Health & lifestyle ──
  cur.section("Health & lifestyle");
  const h = d.clinical.health;
  if (!h) cur.empty("No health profile recorded yet.");
  else {
    cur.row("Life stage", toText(h.lifeStage));
    cur.row("Contraception", toText(h.contraception));
    cur.row("Medical conditions", toText(h.conditions), h.conditions?.length ? COLORS.warn : COLORS.charcoal);
    cur.row("Diet type", toText(h.diet));
    cur.row("Diet balance", toText(h.dietBalance));
    cur.row("Smoke", toText(h.smoke));
    cur.row("Alcohol", toText(h.alcohol));
    cur.row("Daily water", toText(h.water));
    cur.row("Exercise", toText(h.exercise));
    cur.row("Sleep quality", toText(h.sleep));
  }

  // ── Medications ──
  cur.section("Medications & supplements");
  if (d.meds.length === 0) cur.empty("No medications listed.");
  else {
    for (const m of d.meds) {
      cur.row(m.category || "Medication", m.name);
    }
  }

  // ── Blood markers ──
  cur.section("Blood markers", d.blood.length > 0 ? COLORS.gold : COLORS.muted);
  if (d.blood.length === 0) cur.empty("No blood results recorded yet.");
  else {
    // Group by category
    const groups: Record<string, typeof d.blood> = {};
    for (const b of d.blood) {
      const k = (b.category as string) || "Other";
      (groups[k] ??= []).push(b);
    }
    for (const [cat, items] of Object.entries(groups)) {
      cur.paragraph(cat.toUpperCase(), COLORS.gold, 8);
      for (const b of items) {
        const marker = String(b.marker);
        const value = b.value;
        const unit = String(b.unit ?? BLOOD_RANGES[marker]?.unit ?? "");
        let status = b.status as string | null;
        let tone: RGB = COLORS.charcoal;
        if (value != null && !Number.isNaN(Number(value))) {
          const s = evaluate(marker, Number(value));
          status = status ?? s;
          if (s === "low" || s === "high") tone = COLORS.warn;
          else if (s === "normal") tone = COLORS.good;
        }
        const label = status ? `${value ?? "—"} ${unit} · ${statusLabel?.(status as any) ?? status}` : `${value ?? "—"} ${unit}`;
        cur.row(marker, label, tone);
      }
    }
  }

  // ── AI summaries ──
  if (d.summaries.length > 0) {
    cur.section("AI summaries");
    for (const s of d.summaries) {
      const payload = s.payload as Record<string, unknown> | null;
      const text = payload?.summary || payload?.text || payload?.body || JSON.stringify(payload);
      cur.card(String(s.kind).replace(/_/g, " "), [
        { label: "Updated", value: fmtDate(s.updated_at as string) },
        { value: typeof text === "string" ? text : JSON.stringify(text) },
      ]);
    }
  }

  // ── Goals ──
  cur.section("Goals");
  if (d.goals.length === 0) cur.empty("No goals set yet.");
  else {
    for (const g of d.goals) {
      const updates = d.goalUpdates.filter((u: any) => u.goal_id === g.id);
      cur.card(g.title || g.kind, [
        { label: "Status", value: g.status, tone: g.status === "achieved" ? COLORS.good : g.status === "future" ? COLORS.muted : COLORS.charcoal },
        { label: "Challenge", value: g.challenge || "" },
        { label: "Target", value: g.target_text || (g.target_value ? `${g.target_value} ${g.unit ?? ""}` : "") },
        { label: "Target date", value: fmtDate(g.target_date) },
        { label: "Progress", value: `${g.current_value} ${g.unit ?? ""} (from ${g.start_value})` },
        { label: "Notes", value: g.notes || "" },
        { label: "Updates", value: updates.length ? `${updates.length} logged` : "" },
      ]);
      for (const u of updates.slice(0, 5)) {
        cur.paragraph(`• ${fmtDate(u.created_at)} — ${u.note ?? ""}`, COLORS.muted, 8);
      }
    }
  }

  // ── Professional ──
  cur.section("Professional / clinician");
  const pro = d.clinical.professional;
  if (!pro?.name) cur.empty("No professional saved.");
  else {
    cur.row("Name", pro.name || "");
    cur.row("Type", pro.professional_type || "");
    cur.row("Clinic", pro.clinic || "");
    cur.row("Consultation date", fmtDate(pro.consultation_date));
    cur.row("Notes", pro.notes || "");
    cur.row("Instagram", pro.instagram_handle || "");
    cur.row("Website", pro.website_url || "");
    cur.row("Booking", pro.booking_url || "");
  }

  // ── Appointments ──
  cur.section("Appointments");
  if (d.appts.length === 0) cur.empty("No appointments logged.");
  else {
    for (const a of d.appts) {
      cur.card(`${fmtDate(a.appointment_date)}${a.appointment_time ? ` · ${a.appointment_time}` : ""}`, [
        { label: "Professional", value: a.professional_name || "" },
        { label: "Type", value: a.professional_type || "" },
        { label: "Clinic", value: a.clinic_name || "" },
        { label: "Reason", value: a.reason || "" },
        { label: "Notes", value: a.notes || "" },
        { label: "Status", value: a.status || "" },
        { label: "Follow-up needed", value: a.follow_up_needed ? "Yes" : "" },
      ]);
    }
  }

  // ── Products: on-shelf, wishlist, off-shelf, favourites ──
  const renderProducts = (title: string, items: typeof d.products) => {
    cur.section(title);
    if (items.length === 0) { cur.empty("None."); return; }
    for (const p of items) {
      cur.card(`${p.brand ? p.brand + " — " : ""}${p.name}`, [
        { label: "Category", value: p.category || "" },
        { label: "Rating", value: p.rating ? `${p.rating}/5` : "" },
        { label: "AI match", value: p.match_score ? `${p.match_score}/5` : "" },
        { label: "Times used", value: p.use_count ? String(p.use_count) : "" },
        { label: "Last used", value: fmtDate(p.last_used_at) },
        { label: "Added", value: fmtDate(p.added_to_shelf_at) },
        { label: "Reason off shelf", value: p.off_shelf_reason || "" },
        { label: "Source", value: p.source_url || "" },
        { label: "AI summary", value: p.ai_summary || "" },
        { label: "Key ingredients", value: toText(p.key_ingredients) },
        { label: "Ingredients", value: (p.ingredients ?? []).join(", ") },
      ]);
    }
  };
  renderProducts("On-shelf products", d.products.filter(p => p.on_shelf));
  renderProducts("Wishlist", d.products.filter(p => p.on_wishlist));
  renderProducts("Off-shelf products", d.products.filter(p => !p.on_shelf && !p.on_wishlist && p.previously_on_shelf));
  renderProducts("Favourites", d.products.filter(p => p.on_favourite));

  // ── Product ratings (historic) ──
  if (d.ratings.length > 0) {
    cur.section("Product ratings");
    for (const r of d.ratings) {
      cur.card(`${r.product_brand ? r.product_brand + " — " : ""}${r.product_name}`, [
        { label: "Rating", value: r.rating ? `${r.rating}/5` : "" },
        { label: "When", value: fmtDate(r.created_at) },
        { label: "Notes", value: r.notes || "" },
      ]);
    }
  }

  // ── Tools ──
  cur.section("Tools");
  if (d.tools.length === 0) cur.empty("No tools added.");
  else {
    for (const t of d.tools) {
      cur.card(`${t.brand ? t.brand + " — " : ""}${t.name}`, [
        { label: "Category", value: t.category || "" },
        { label: "Rating", value: t.rating ? `${t.rating}/5` : "" },
        { label: "Times used", value: t.use_count ? String(t.use_count) : "" },
        { label: "Last used", value: fmtDate(t.last_used_at) },
        { label: "Favourite", value: t.on_favourite ? "Yes" : "" },
        { label: "On shelf", value: t.on_shelf ? "Yes" : "" },
        { label: "Notes", value: t.notes || "" },
        { label: "Source", value: t.source_url || "" },
      ]);
    }
  }

  // ── Wash days ──
  cur.section("Wash day log");
  if (d.washes.length === 0) cur.empty("No wash days logged yet.");
  else {
    for (const w of d.washes) {
      const steps = Array.isArray(w.steps) ? (w.steps as any[]) : [];
      const stepText = steps.map((s: any) => s?.name || s?.title || s?.product || JSON.stringify(s)).filter(Boolean).join(" → ");
      cur.card(fmtDate(w.wash_date), [
        { label: "Duration", value: w.duration_min ? `${w.duration_min} min` : "" },
        { label: "Scalp feel", value: w.scalp_feel || "" },
        { label: "Breakage", value: w.breakage || "" },
        { label: "Hair feel", value: w.hair_feel_note || "" },
        { label: "Style after", value: w.style_after || "" },
        { label: "Stress", value: w.stress_level != null ? `${w.stress_level}/10` : "" },
        { label: "Steps", value: stepText },
        { label: "Heat treatment", value: toText(w.heat_treatment) },
        { label: "AI insight", value: w.ai_insight || "" },
      ]);
    }
  }

  // ── Journal ──
  cur.section("Style journal");
  if (d.journal.length === 0) cur.empty("No journal entries yet.");
  else {
    for (const j of d.journal) {
      cur.card(`${fmtDate(j.entry_date)}${j.title ? ` — ${j.title}` : ""}`, [
        { label: "Mood", value: j.mood || "" },
        { label: "Products used", value: (j.products_used ?? []).join(", ") },
        { label: "Photos", value: (j.photo_paths ?? []).length ? `${(j.photo_paths ?? []).length} attached` : "" },
        { value: j.note || "" },
      ]);
    }
  }

  // ── Moodboards ──
  cur.section("Moodboards");
  if (d.boards.length === 0) cur.empty("No moodboards created.");
  else {
    for (const b of d.boards) {
      const imgs = d.boardImages.filter((i: any) => i.board_id === b.id);
      cur.card(`${b.emoji ?? ""} ${b.name}`.trim(), [
        { label: "Created", value: fmtDate(b.created_at) },
        { label: "Favourites board", value: b.is_favourites ? "Yes" : "" },
        { label: "Images", value: `${imgs.length}` },
        { label: "Captions", value: imgs.map((i: any) => i.caption).filter(Boolean).join(" · ") },
      ]);
    }
  }

  // ── Ingredient flags ──
  cur.section("Flagged ingredients");
  if (d.ingLists.length === 0) cur.empty("No ingredient flags yet.");
  else {
    for (const i of d.ingLists) {
      cur.row(i.ingredient, `${i.reason || ""}${i.product_count ? ` · in ${i.product_count} products` : ""}`, COLORS.warn);
    }
  }

  // Re-paint footer with correct totals.
  const total = doc.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    drawFooter(doc, p, total);
  }

  const safeName = displayName.replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "") || "client";
  const fileName = `STRAND-full-profile-${safeName}-${new Date().toISOString().slice(0, 10)}.pdf`;
  return { blob: doc.output("blob"), fileName };
}
