// Generates a STRAND-branded PDF report of the user's auto-derived flagged
// ingredients (ingredients that appear in 3+ of their saved products). Uses
// jsPDF directly — no DOM rasterization — so the output is sharp,
// selectable text, and small file size.
//
// Branding cues:
//   - Warm sand page background (#F2E8D9)
//   - Gold accent rule + section labels (#C49A3C)
//   - Charcoal body text (#2C2416)
//   - Serif display (Times) for headings, Helvetica for body — closest match
//     to Playfair Display + Jost using jsPDF's built-in font set, and avoids
//     shipping a font file just for this report.
import { jsPDF } from "jspdf";
import type { IngredientListRow } from "@/hooks/useIngredientLists";

interface ReportInput {
  userName: string;
  flags: IngredientListRow[];
}

// HSL → RGB tuple. STRAND tokens are HSL so we mirror them here for accuracy.
const COLORS = {
  background: [242, 232, 217] as [number, number, number], // #F2E8D9
  card: [253, 248, 242] as [number, number, number], // #FDF8F2
  border: [221, 208, 184] as [number, number, number], // #DDD0B8
  charcoal: [44, 36, 22] as [number, number, number], // #2C2416
  muted: [122, 106, 84] as [number, number, number], // #7A6A54
  gold: [196, 154, 60] as [number, number, number], // #C49A3C
  warn: [184, 112, 32] as [number, number, number], // #B87020
  good: [90, 138, 90] as [number, number, number], // #5A8A5A
};

const PAGE = { w: 210, h: 297 }; // A4 portrait, mm
const MARGIN = 18;
const CONTENT_W = PAGE.w - MARGIN * 2;

function paintBackground(doc: jsPDF) {
  doc.setFillColor(...COLORS.background);
  doc.rect(0, 0, PAGE.w, PAGE.h, "F");
}

function drawHeader(doc: jsPDF) {
  // Wordmark — use bold helvetica with letter-spacing-style padding via text
  // call options. Times rendered odd kerning on capital Y/W in QA.
  doc.setFont("helvetica", "normal");
  doc.setFontSize(26);
  doc.setTextColor(...COLORS.charcoal);
  doc.text("STRAND", MARGIN, 24, { charSpace: 1.2 });

  // Tiny tag under the mark
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.muted);
  doc.text("HAIR  ·  INGREDIENTS  ·  CARE", MARGIN, 29, { charSpace: 0.4 });

  // Right-aligned report label
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.gold);
  doc.text("INGREDIENT REPORT", PAGE.w - MARGIN, 24, { align: "right", charSpace: 0.6 });

  // Gold rule under header
  doc.setDrawColor(...COLORS.gold);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, 34, PAGE.w - MARGIN, 34);
}

function drawFooter(doc: jsPDF, page: number, totalPages: number) {
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.2);
  doc.line(MARGIN, PAGE.h - 16, PAGE.w - MARGIN, PAGE.h - 16);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text("Generated by STRAND", MARGIN, PAGE.h - 10);
  doc.text(
    `Page ${page} of ${totalPages}`,
    PAGE.w - MARGIN,
    PAGE.h - 10,
    { align: "right" },
  );
}

/** Make sure there's room for `needed` mm before the footer; otherwise break. */
function ensureSpace(
  doc: jsPDF,
  cursorY: number,
  needed: number,
  onNewPage: () => number,
): number {
  if (cursorY + needed > PAGE.h - 22) {
    doc.addPage();
    paintBackground(doc);
    drawHeader(doc);
    return onNewPage();
  }
  return cursorY;
}

function drawIntro(
  doc: jsPDF,
  userName: string,
  flagCount: number,
): number {
  let y = 46;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(20);
  doc.setTextColor(...COLORS.charcoal);
  doc.text("Your Ingredient Profile", MARGIN, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.muted);
  const today = new Date().toLocaleDateString(undefined, {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  doc.text(`Prepared for ${userName} · ${today}`, MARGIN, y);
  y += 9;

  // Intro paragraph
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.charcoal);
  const intro =
    "This report lists the ingredients that appear in 3 or more of this user's saved products inside the STRAND app. Treat it as an educational starting point for consultations - it shows what this user is consistently exposed to, not a clinical assessment.";
  const introLines = doc.splitTextToSize(intro, CONTENT_W);
  doc.text(introLines, MARGIN, y);
  y += introLines.length * 4.6 + 4;

  // Single summary chip
  const chipY = y;
  const chipH = 18;
  const chipW = CONTENT_W;

  doc.setFillColor(...COLORS.card);
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.2);
  doc.roundedRect(MARGIN, chipY, chipW, chipH, 2, 2, "FD");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.gold);
  doc.text("FLAGGED", MARGIN + 5, chipY + 6);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(20);
  doc.setTextColor(...COLORS.charcoal);
  doc.text(String(flagCount), MARGIN + 5, chipY + 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  doc.text(
    flagCount === 1 ? "ingredient flagged" : "ingredients flagged",
    MARGIN + 16,
    chipY + 14,
  );

  return chipY + chipH + 10;
}

function drawSectionHeading(doc: jsPDF, y: number, label: string, accent: [number, number, number]) {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...accent);
  doc.text(label.toUpperCase(), MARGIN, y);

  doc.setDrawColor(...accent);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y + 1.6, MARGIN + 14, y + 1.6);

  return y + 6;
}

function drawIngredientRow(
  doc: jsPDF,
  y: number,
  row: IngredientListRow,
  accent: [number, number, number],
): number {
  const rowH = 13;

  // Card background
  doc.setFillColor(...COLORS.card);
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.15);
  doc.roundedRect(MARGIN, y, CONTENT_W, rowH, 1.5, 1.5, "FD");

  // Status dot
  doc.setFillColor(...accent);
  doc.circle(MARGIN + 4, y + rowH / 2, 1.1, "F");

  // Ingredient name
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.charcoal);
  doc.text(row.ingredient, MARGIN + 8, y + 5.6);

  // Reason
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text(row.reason, MARGIN + 8, y + 10);

  // Right-side count
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...accent);
  doc.text(
    `${row.product_count}×`,
    PAGE.w - MARGIN - 4,
    y + 8,
    { align: "right" },
  );

  return y + rowH + 3;
}

function drawEmptyState(doc: jsPDF, y: number, message: string): number {
  doc.setFillColor(...COLORS.card);
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.15);
  doc.roundedRect(MARGIN, y, CONTENT_W, 14, 1.5, 1.5, "FD");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  doc.text(message, MARGIN + 5, y + 8.5);
  return y + 14 + 3;
}

export function generateIngredientReportPdf(input: ReportInput) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  paintBackground(doc);
  drawHeader(doc);
  let y = drawIntro(doc, input.userName, input.flags.length);

  const continuationY = () => 46;

  // FLAGGED INGREDIENTS section — single unified list. An ingredient is
  // flagged when it appears in 3+ of the user's saved products. Educational,
  // no good/bad framing.
  y = ensureSpace(doc, y, 18, continuationY);
  y = drawSectionHeading(doc, y, "Flagged ingredients", COLORS.gold);

  if (input.flags.length === 0) {
    y = drawEmptyState(
      doc,
      y,
      "No flagged ingredients yet - save 3 or more products that share an ingredient to populate.",
    );
  } else {
    for (const row of input.flags) {
      y = ensureSpace(doc, y, 16, continuationY);
      y = drawIngredientRow(doc, y, row, COLORS.gold);
    }
  }

  // Footers across all pages
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    drawFooter(doc, p, totalPages);
  }

  const safeName = input.userName.replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "") || "client";
  const dateStamp = new Date().toISOString().slice(0, 10);
  const fileName = `STRAND-ingredient-report-${safeName}-${dateStamp}.pdf`;
  const blob = doc.output("blob");
  return { blob, fileName };
}
