// STRAND — Professional Snapshot PDF
// A 1–2 page clinical-style summary for a trichologist, dermatologist or
// hairstylist meeting the client for the first time. Distinct from the
// full-profile PDF: only what a professional needs to assess hair & scalp
// health fast. Section order is priority order — do not reorder.

import { jsPDF } from "jspdf";
import { supabase } from "@/integrations/supabase/client";
import { loadClinicalContext } from "@/lib/clinicalContext";
import { BLOOD_RANGES, evaluate, statusLabel } from "@/data/bloodRanges";

// ─── Brand tokens (mirrors fullProfilePdf.ts) ─────────────────────────────
const PAGE = { w: 210, h: 297 };
const MARGIN = 16;
const CONTENT_W = PAGE.w - MARGIN * 2;

const COLORS = {
  background: [242, 232, 217] as [number, number, number],
  card: [253, 248, 242] as [number, number, number],
  border: [221, 208, 184] as [number, number, number],
  charcoal: [44, 36, 22] as [number, number, number],
  muted: [122, 106, 84] as [number, number, number],
  gold: [196, 154, 60] as [number, number, number],
  warn: [184, 112, 32] as [number, number, number],
  good: [90, 138, 90] as [number, number, number],
};

type RGB = [number, number, number];

// Core hair-relevant markers always surfaced (even when normal).
const CORE_HAIR_MARKERS = new Set<string>([
  "Ferritin",
  "Serum Iron",
  "Transferrin Saturation",
  "Vitamin D",
  "Vitamin B12",
  "Zinc",
  "TSH",
  "Free T3",
  "Free T4",
  "Thyroid Antibodies (TPO)",
]);

// Health conditions/life-stages known to affect hair.
const HAIR_HEALTH_KEYWORDS = [
  "thyroid", "hypothyroid", "hyperthyroid",
  "pcos", "polycystic",
  "anaemia", "anemia", "iron deficien",
  "postpartum", "post-partum", "post natal", "postnatal",
  "menopaus", "perimenopaus",
  "alopecia", "telogen", "androgenic",
  "lupus", "eczema", "psoriasis", "seborrh", "dermatitis",
];

const HAIR_LIFESTAGE_KEYWORDS = [
  "pregnan", "postpartum", "post-partum", "breastfeed",
  "perimenopaus", "menopaus",
];

// Medications/supplements with documented hair-growth or hair-loss signal.
const HAIR_MED_KEYWORDS = [
  "minoxidil", "finasteride", "dutasteride", "spironolactone",
  "isotretinoin", "accutane", "retinoid",
  "biotin", "iron", "ferrous", "vitamin d", "zinc", "collagen",
  "levothyroxine", "thyroxine", "carbimazole",
  "beta blocker", "propranolol", "atenolol",
  "warfarin", "heparin", "anticoagulant",
  "statin", "atorvastatin", "simvastatin",
  "lithium", "valproate", "sodium valproate",
  "methotrexate", "chemotherapy", "chemo",
  "tamoxifen", "letrozole", "anastrozole",
  "hormone", "hrt", "contracepti",
];

// ─── Utilities ────────────────────────────────────────────────────────────
const fmtDate = (iso?: string | null): string => {
  if (!iso) return "";
  try {
    return new Date(iso).toLocaleDateString(undefined, {
      day: "numeric", month: "short", year: "numeric",
    });
  } catch { return iso; }
};

const uniqLower = (xs: string[]) =>
  Array.from(new Set(xs.filter(Boolean).map(x => x.trim())));

const anyKeyword = (needle: string, keywords: string[]) => {
  const s = needle.toLowerCase();
  return keywords.some(k => s.includes(k));
};

const mostCommon = <T,>(xs: T[]): T | null => {
  const counts = new Map<T, number>();
  for (const x of xs) if (x != null) counts.set(x, (counts.get(x) ?? 0) + 1);
  let best: T | null = null;
  let n = 0;
  counts.forEach((c, v) => { if (c > n) { n = c; best = v; } });
  return best;
};

// ─── Layout primitives (mirrors fullProfilePdf.ts Cursor) ─────────────────
function paintBackground(doc: jsPDF) {
  doc.setFillColor(...COLORS.background);
  doc.rect(0, 0, PAGE.w, PAGE.h, "F");
}

function drawHeader(doc: jsPDF, subtitle: string) {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(22);
  doc.setTextColor(...COLORS.charcoal);
  doc.text("STRAND", MARGIN, 20, { charSpace: 1.2 });
  doc.setFontSize(7.5);
  doc.setTextColor(...COLORS.gold);
  doc.text("PROFESSIONAL SNAPSHOT", PAGE.w - MARGIN, 20, { align: "right", charSpace: 0.5 });
  doc.setDrawColor(...COLORS.gold);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, 24, PAGE.w - MARGIN, 24);
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  doc.text(subtitle, MARGIN, 30);
}

function drawFooter(doc: jsPDF, page: number, total: number) {
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.15);
  doc.line(MARGIN, PAGE.h - 14, PAGE.w - MARGIN, PAGE.h - 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...COLORS.muted);
  doc.text("Generated by STRAND · Clinical snapshot — share at your discretion", MARGIN, PAGE.h - 9);
  doc.text(`Page ${page} of ${total}`, PAGE.w - MARGIN, PAGE.h - 9, { align: "right" });
}

class Cursor {
  y: number;
  constructor(public doc: jsPDF, public subtitle: string) { this.y = 36; }

  ensure(needed: number) {
    if (this.y + needed <= PAGE.h - 18) return;
    this.doc.addPage();
    paintBackground(this.doc);
    drawHeader(this.doc, this.subtitle);
    this.y = 36;
  }

  section(label: string, tone: RGB = COLORS.gold) {
    this.ensure(12);
    this.y += 3;
    this.doc.setFont("helvetica", "normal");
    this.doc.setFontSize(8);
    this.doc.setTextColor(...tone);
    this.doc.text(label.toUpperCase(), MARGIN, this.y, { charSpace: 0.5 });
    this.doc.setDrawColor(...tone);
    this.doc.setLineWidth(0.25);
    this.doc.line(MARGIN, this.y + 1.4, MARGIN + 16, this.y + 1.4);
    this.y += 5;
  }

  row(label: string, value: string, tone: RGB = COLORS.charcoal) {
    if (!value) return;
    const lines = this.doc.splitTextToSize(value, CONTENT_W - 42);
    const h = Math.max(9, 5 + lines.length * 3.6);
    this.ensure(h + 1.5);
    this.doc.setFillColor(...COLORS.card);
    this.doc.setDrawColor(...COLORS.border);
    this.doc.setLineWidth(0.12);
    this.doc.roundedRect(MARGIN, this.y, CONTENT_W, h, 1.2, 1.2, "FD");
    this.doc.setFont("helvetica", "normal");
    this.doc.setFontSize(7);
    this.doc.setTextColor(...COLORS.muted);
    this.doc.text(label, MARGIN + 4, this.y + 4);
    this.doc.setFontSize(8.5);
    this.doc.setTextColor(...tone);
    this.doc.text(lines, MARGIN + 34, this.y + 4);
    this.y += h + 1.5;
  }

  paragraph(text: string, tone: RGB = COLORS.charcoal, size = 8.5) {
    if (!text) return;
    const lines = this.doc.splitTextToSize(text, CONTENT_W - 6);
    const h = 3 + lines.length * (size * 0.42);
    this.ensure(h + 1.5);
    this.doc.setFont("helvetica", "normal");
    this.doc.setFontSize(size);
    this.doc.setTextColor(...tone);
    this.doc.text(lines, MARGIN + 2, this.y + 3);
    this.y += h + 1.5;
  }

  tagRow(text: string) {
    if (!text) return;
    this.ensure(7);
    this.doc.setFont("helvetica", "normal");
    this.doc.setFontSize(8.5);
    this.doc.setTextColor(...COLORS.charcoal);
    const lines = this.doc.splitTextToSize(text, CONTENT_W);
    this.doc.text(lines, MARGIN, this.y + 3);
    this.y += 3 + lines.length * 3.8 + 1;
  }
}

// ─── Data fetch ──────────────────────────────────────────────────────────
async function fetchAll(userId: string) {
  const [
    profile, clinical, blood, goals, meds, products, washes, ingLists,
    milestone, before,
  ] = await Promise.all([
    supabase.from("profiles").select("display_name, birth_year").eq("user_id", userId).maybeSingle(),
    loadClinicalContext(),
    supabase.from("blood_results").select("marker, value, unit, status, category").eq("user_id", userId),
    supabase.from("user_goals").select("id, title, kind, status, challenge, target_text, target_value, unit, target_date").eq("user_id", userId).order("created_at", { ascending: false }),
    supabase.from("user_medications").select("name, category").eq("user_id", userId),
    supabase.from("user_products").select("name, brand, on_shelf, match_score, ai_summary").eq("user_id", userId).eq("on_shelf", true),
    supabase.from("wash_days").select("wash_date, scalp_feel, breakage, heat_treatment").eq("user_id", userId).order("wash_date", { ascending: false }).limit(20),
    supabase.from("ingredient_lists").select("ingredient, list_kind, reason").eq("user_id", userId).eq("list_kind", "avoid"),
    supabase.from("user_milestone_photos").select("storage_path, caption, taken_on").eq("user_id", userId).order("taken_on", { ascending: false }).limit(3),
    supabase.from("user_before_photos").select("storage_path, created_at").eq("user_id", userId).order("created_at", { ascending: false }).limit(3),
  ]);

  return {
    profile: profile.data,
    clinical,
    blood: blood.data ?? [],
    goals: goals.data ?? [],
    meds: meds.data ?? [],
    products: products.data ?? [],
    washes: washes.data ?? [],
    ingLists: ingLists.data ?? [],
    milestone: milestone.data ?? [],
    before: before.data ?? [],
  };
}

async function loadImageAsDataUrl(bucket: string, path: string): Promise<{ dataUrl: string; w: number; h: number } | null> {
  try {
    const signed = await supabase.storage.from(bucket).createSignedUrl(path, 60);
    const url = signed.data?.signedUrl;
    if (!url) return null;
    const res = await fetch(url);
    if (!res.ok) return null;
    const blob = await res.blob();
    const dataUrl: string = await new Promise((resolve, reject) => {
      const r = new FileReader();
      r.onload = () => resolve(r.result as string);
      r.onerror = reject;
      r.readAsDataURL(blob);
    });
    // Get natural dimensions
    const dim = await new Promise<{ w: number; h: number }>((resolve) => {
      const img = new Image();
      img.onload = () => resolve({ w: img.naturalWidth, h: img.naturalHeight });
      img.onerror = () => resolve({ w: 1, h: 1 });
      img.src = dataUrl;
    });
    return { dataUrl, w: dim.w, h: dim.h };
  } catch {
    return null;
  }
}

// ─── Aggregations ────────────────────────────────────────────────────────
function washAggregate(washes: { wash_date: string; scalp_feel: string | null; breakage: string | null }[]) {
  if (washes.length === 0) return null;
  const dates = washes
    .map(w => new Date(w.wash_date).getTime())
    .filter(t => !Number.isNaN(t))
    .sort((a, b) => a - b);
  let avgDays: number | null = null;
  if (dates.length >= 2) {
    const gaps: number[] = [];
    for (let i = 1; i < dates.length; i++) gaps.push((dates[i] - dates[i - 1]) / 86_400_000);
    avgDays = Math.round((gaps.reduce((a, b) => a + b, 0) / gaps.length) * 10) / 10;
  }
  const scalp = mostCommon(washes.map(w => (w.scalp_feel || "").trim()).filter(Boolean));
  const breakageVals = washes.map(w => (w.breakage || "").trim()).filter(Boolean);
  const breakageMode = mostCommon(breakageVals);
  // Trend: compare first vs second half severity (looks for keyword weight).
  const weight = (v: string) => {
    const s = v.toLowerCase();
    if (s.includes("none") || s.includes("minimal")) return 0;
    if (s.includes("some") || s.includes("mild")) return 1;
    if (s.includes("noticeable") || s.includes("moderate")) return 2;
    if (s.includes("lots") || s.includes("severe") || s.includes("heavy")) return 3;
    return 1;
  };
  let trend: "improving" | "worsening" | "stable" | null = null;
  if (breakageVals.length >= 4) {
    const ordered = washes
      .slice()
      .sort((a, b) => new Date(a.wash_date).getTime() - new Date(b.wash_date).getTime())
      .map(w => w.breakage || "")
      .filter(Boolean);
    const mid = Math.floor(ordered.length / 2);
    const first = ordered.slice(0, mid).map(weight);
    const last = ordered.slice(mid).map(weight);
    const avg = (xs: number[]) => xs.reduce((a, b) => a + b, 0) / Math.max(xs.length, 1);
    const delta = avg(last) - avg(first);
    if (delta <= -0.4) trend = "improving";
    else if (delta >= 0.4) trend = "worsening";
    else trend = "stable";
  }
  return { count: washes.length, avgDays, scalp, breakageMode, trend };
}

// ─── Generator ────────────────────────────────────────────────────────────
export async function generateProfessionalSnapshotPdf(
  extraNote?: string,
): Promise<{ blob: Blob; fileName: string }> {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error("Not signed in");

  const d = await fetchAll(user.id);

  const displayName =
    d.clinical.basic?.name?.trim() ||
    d.profile?.display_name?.trim() ||
    (user.user_metadata?.display_name as string | undefined)?.trim() ||
    (user.email ? user.email.split("@")[0] : "STRAND Member");

  const age = d.clinical.basic?.age
    ?? (d.profile?.birth_year ? new Date().getFullYear() - Number(d.profile.birth_year) : null);

  const today = new Date();
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  paintBackground(doc);
  const subtitle = `${displayName} · Professional snapshot · ${today.toLocaleDateString()}`;
  drawHeader(doc, subtitle);
  const cur = new Cursor(doc, subtitle);

  // ── 1. Header block ─────────────────────────────────────────────────
  cur.doc.setFont("helvetica", "normal");
  cur.doc.setFontSize(16);
  cur.doc.setTextColor(...COLORS.charcoal);
  cur.doc.text(displayName, MARGIN, cur.y + 4);
  cur.doc.setFontSize(9);
  cur.doc.setTextColor(...COLORS.muted);
  const meta = [
    age ? `Age ${age}` : null,
    `Generated ${today.toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" })}`,
  ].filter(Boolean).join("  ·  ");
  cur.doc.text(meta, MARGIN, cur.y + 10);
  cur.y += 14;

  const hair = d.clinical.hair;
  const quick = [
    hair?.texture?.[0] ? `Texture: ${hair.texture[0]}` : null,
    hair?.density?.[0] ? `Density: ${hair.density[0]}` : null,
    hair?.porosity?.[0] ? `Porosity: ${hair.porosity[0]}` : null,
    hair?.scalp?.[0] ? `Scalp: ${hair.scalp[0]}` : null,
  ].filter(Boolean).join("   ·   ");
  if (quick) cur.tagRow(quick);

  // ── 2. Reason for visit ─────────────────────────────────────────────
  const activeGoals = d.goals.filter((g: any) => g.status === "active" || g.status === "in_progress" || !g.status).slice(0, 2);
  const areas = hair?.areas ?? [];
  if (activeGoals.length > 0 || areas.length > 0) {
    cur.section("Reason for visit");
    for (const g of activeGoals) {
      const target = g.target_text || (g.target_value ? `${g.target_value} ${g.unit ?? ""}` : "");
      const dateStr = g.target_date ? ` (by ${fmtDate(g.target_date)})` : "";
      const detail = [g.challenge, target && `Target: ${target}`].filter(Boolean).join(" · ");
      cur.row(String(g.kind || "Goal"), `${g.title || ""}${detail ? " — " + detail : ""}${dateStr}`);
    }
    if (areas.length > 0) cur.row("Areas of concern", areas.join(", "), COLORS.warn);
  }

  // ── 3. Hair & scalp profile ─────────────────────────────────────────
  if (hair) {
    const rows: [string, string, RGB?][] = [
      ["Strand diameter", (hair.diameter ?? []).join(", ")],
      ["Surface texture", (hair.texture ?? []).join(", ")],
      ["Density", (hair.density ?? []).join(", ")],
      ["Porosity", (hair.porosity ?? []).join(", ")],
      ["Elasticity", (hair.elasticity ?? []).join(", ")],
      ["Scalp condition", (hair.scalp ?? []).join(", ")],
      ["Diagnosed conditions", (hair.diagnosed ?? []).join(", "), COLORS.warn],
    ];
    if (rows.some(([, v]) => v)) {
      cur.section("Hair & scalp profile");
      for (const [l, v, tone] of rows) if (v) cur.row(l, v, tone);
    }
  }

  // ── 4. Chemical & heat history ──────────────────────────────────────
  const style = d.clinical.style;
  if (style) {
    const colour = (style.colour ?? []).join(", ");
    const chem = (style.chemical_history ?? []).join(", ");
    const cur_style = style.current_hairstyle || "";
    const howLong = style.howLong || (style.howLongNum && style.howLongUnit ? `${style.howLongNum} ${style.howLongUnit}` : "");
    // Heat-treatment frequency: count wash days with heat in the recent window.
    const heatCount = d.washes.filter((w: any) => {
      const h = w.heat_treatment;
      if (!h) return false;
      if (typeof h === "boolean") return h;
      if (Array.isArray(h)) return h.length > 0;
      if (typeof h === "object") return Object.values(h).some(Boolean);
      return String(h).toLowerCase() !== "none";
    }).length;
    const heatText = d.washes.length > 0
      ? `${heatCount} of last ${d.washes.length} wash days`
      : "";
    if (colour || chem || cur_style || heatText) {
      cur.section("Chemical & heat history");
      if (colour) cur.row("Colour history", colour);
      if (chem) cur.row("Chemical history", chem, COLORS.warn);
      if (cur_style) cur.row("Current style", howLong ? `${cur_style} · ${howLong}` : cur_style);
      if (heatText) cur.row("Heat treatment", heatText);
    }
  }

  // ── 5. Relevant health context ──────────────────────────────────────
  const health = d.clinical.health;
  const relConditions = uniqLower([
    ...(health?.conditions ?? []),
    ...(health?.lifeStage ?? []).filter(s => anyKeyword(s, HAIR_LIFESTAGE_KEYWORDS)),
  ]).filter(c => anyKeyword(c, HAIR_HEALTH_KEYWORDS) || anyKeyword(c, HAIR_LIFESTAGE_KEYWORDS));
  const relMeds = d.meds.filter((m: any) =>
    anyKeyword(m.name || "", HAIR_MED_KEYWORDS) || anyKeyword(m.category || "", HAIR_MED_KEYWORDS)
  );
  const dietFlag: string[] = [];
  if (health?.diet && /veg|vegan|plant/i.test(health.diet)) dietFlag.push("plant-based diet — screen iron / B12 / zinc");
  if ((health?.dietBalance ?? []).some(x => /low protein|low iron/i.test(x))) dietFlag.push("self-reported low iron/protein intake");
  const sleepPoor = (health?.sleep ?? []).some(x => /poor|broken|<\s*6/i.test(x));
  const stressFlag: string[] = [];
  if (sleepPoor) stressFlag.push("poor sleep");
  if (relConditions.length || relMeds.length || dietFlag.length || stressFlag.length) {
    cur.section("Relevant health context");
    if (relConditions.length) cur.row("Conditions / life stage", relConditions.join(", "), COLORS.warn);
    if (relMeds.length) cur.row("Meds & supplements", relMeds.map((m: any) => m.name).join(", "), COLORS.warn);
    if (dietFlag.length) cur.row("Diet flag", dietFlag.join("; "));
    if (stressFlag.length) cur.row("Lifestyle", stressFlag.join(", "));
  }

  // ── 6. Blood markers (flagged + core hair markers) ──────────────────
  if (d.blood.length > 0) {
    type Row = { marker: string; value: string; tone: RGB };
    const shown: Row[] = [];
    let normalOther = 0;
    for (const b of d.blood) {
      const marker = String(b.marker);
      const val = b.value;
      const unit = String(b.unit ?? BLOOD_RANGES[marker]?.unit ?? "");
      const status = (val != null && !Number.isNaN(Number(val)))
        ? evaluate(marker, Number(val))
        : (b.status as any) || "untested";
      const abnormal = status === "low" || status === "high";
      const isCore = CORE_HAIR_MARKERS.has(marker);
      if (abnormal) {
        shown.push({
          marker,
          value: `${val ?? "—"} ${unit} · ${statusLabel(status)}`,
          tone: COLORS.warn,
        });
      } else if (isCore && status === "normal") {
        shown.push({
          marker,
          value: `${val ?? "—"} ${unit} · Normal`,
          tone: COLORS.good,
        });
      } else if (status === "normal") {
        normalOther++;
      }
    }
    if (shown.length > 0 || normalOther > 0) {
      cur.section("Blood markers");
      // Abnormal first, then core-normal
      const abnormalRows = shown.filter(r => r.tone === COLORS.warn);
      const normalCore = shown.filter(r => r.tone === COLORS.good);
      for (const r of abnormalRows) cur.row(r.marker, r.value, r.tone);
      for (const r of normalCore) cur.row(r.marker, r.value, r.tone);
      if (normalOther > 0) cur.paragraph(`All other markers within normal range (${normalOther}).`, COLORS.muted, 8);
    }
  }

  // ── 7. Wash & care pattern ──────────────────────────────────────────
  const wagg = washAggregate(d.washes as any);
  if (wagg) {
    cur.section("Wash & care pattern");
    const lines: string[] = [];
    lines.push(`${wagg.count} wash days logged${wagg.avgDays != null ? ` · avg every ${wagg.avgDays} days` : ""}.`);
    if (wagg.scalp) lines.push(`Most common scalp feel: ${wagg.scalp}.`);
    if (wagg.breakageMode) lines.push(`Most common breakage report: ${wagg.breakageMode}.`);
    if (wagg.trend) lines.push(`Breakage trend: ${wagg.trend}.`);
    cur.paragraph(lines.join(" "), COLORS.charcoal, 8.5);
  }

  // ── 8. Ingredient flags ─────────────────────────────────────────────
  const warnProducts = d.products.filter((p: any) =>
    (p.match_score != null && p.match_score <= 2) ||
    /warn|avoid|caution/i.test(p.ai_summary || "")
  );
  if (d.ingLists.length > 0 || warnProducts.length > 0) {
    cur.section("Ingredient flags");
    for (const i of d.ingLists.slice(0, 8)) {
      cur.row(i.ingredient, i.reason || "flagged to avoid", COLORS.warn);
    }
    for (const p of warnProducts.slice(0, 4)) {
      const name = `${p.brand ? p.brand + " — " : ""}${p.name}`;
      cur.row("Product warning", name, COLORS.warn);
    }
  }

  // ── 9. Recent photos ────────────────────────────────────────────────
  const photoSources = d.milestone.length > 0
    ? d.milestone.map((r: any) => ({ bucket: "milestone-photos", path: r.storage_path, caption: r.caption, when: r.taken_on }))
    : d.before.map((r: any) => ({ bucket: "before-photos", path: r.storage_path, caption: null, when: r.created_at }));
  const photos = photoSources.slice(0, 3);
  if (photos.length > 0) {
    const loaded = (await Promise.all(
      photos.map(p => loadImageAsDataUrl(p.bucket, p.path).then(r => r ? { ...p, ...r } : null))
    )).filter(Boolean) as Array<{ dataUrl: string; w: number; h: number; caption: string | null; when: string }>;
    if (loaded.length > 0) {
      cur.section("Recent photos");
      const gap = 4;
      const cellW = (CONTENT_W - gap * (loaded.length - 1)) / loaded.length;
      const cellH = 40;
      cur.ensure(cellH + 8);
      let x = MARGIN;
      for (const p of loaded) {
        // Fit contain
        const ratio = p.w / p.h;
        let iw = cellW, ih = cellW / ratio;
        if (ih > cellH) { ih = cellH; iw = cellH * ratio; }
        const ox = x + (cellW - iw) / 2;
        const oy = cur.y + (cellH - ih) / 2;
        try { cur.doc.addImage(p.dataUrl, "JPEG", ox, oy, iw, ih); } catch { /* skip */ }
        cur.doc.setFontSize(7);
        cur.doc.setTextColor(...COLORS.muted);
        const cap = [fmtDate(p.when), p.caption].filter(Boolean).join(" · ");
        cur.doc.text(cap.slice(0, 40), x, cur.y + cellH + 3);
        x += cellW + gap;
      }
      cur.y += cellH + 6;
    }
  }

  // ── 10. Notes for professional ──────────────────────────────────────
  const newAbnormal = d.blood.filter((b: any) => {
    const v = b.value;
    if (v == null || Number.isNaN(Number(v))) return false;
    const s = evaluate(String(b.marker), Number(v));
    return s === "low" || s === "high";
  });
  const alerts: string[] = [];
  if (newAbnormal.length > 0) {
    const names = newAbnormal.slice(0, 3).map((b: any) => b.marker).join(", ");
    alerts.push(`${newAbnormal.length} abnormal marker${newAbnormal.length === 1 ? "" : "s"} recorded (${names}).`);
  }
  if (hair?.diagnosed?.length) alerts.push(`Existing diagnosis: ${hair.diagnosed.join(", ")}.`);
  if (wagg?.trend === "worsening") alerts.push("Breakage trend worsening across recent wash days.");
  if (extraNote || alerts.length > 0) {
    cur.section("Notes for professional");
    if (extraNote) cur.paragraph(extraNote, COLORS.charcoal, 8.5);
    if (alerts.length > 0) cur.paragraph("⚑ " + alerts.join(" "), COLORS.warn, 8.5);
  }

  // ── Footer ──────────────────────────────────────────────────────────
  const total = doc.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    drawFooter(doc, p, total);
  }

  const safeName = displayName.replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "") || "client";
  const fileName = `STRAND-snapshot-${safeName}-${new Date().toISOString().slice(0, 10)}.pdf`;
  return { blob: doc.output("blob"), fileName };
}
