import { jsPDF } from "jspdf";
import type { BloodStatus } from "@/data/bloodRanges";

interface ProfilePdfInput {
  displayName: string;
  age?: string;
  postcode?: string;
  waterHardness?: string | null;
  hair: {
    diameter?: string | string[];
    porosity?: string | string[];
    density?: string | string[];
    scalp?: string | string[];
    diagnosed?: string[];
  };
  flaggedBlood: { marker: string; value: number; status: BloodStatus; unit: string }[];
  hasAnyBloodValues: boolean;
  medications: string[];
}

const PAGE = { w: 210, h: 297 };
const MARGIN = 18;
const CONTENT_W = PAGE.w - MARGIN * 2;

const COLORS = {
  background: [242, 232, 217] as [number, number, number],
  card: [253, 248, 242] as [number, number, number],
  border: [221, 208, 184] as [number, number, number],
  charcoal: [44, 36, 22] as [number, number, number],
  muted: [122, 106, 84] as [number, number, number],
  gold: [196, 154, 60] as [number, number, number],
  warn: [184, 112, 32] as [number, number, number],
  good: [90, 138, 90] as [number, number, number],
};

function toText(v: unknown): string {
  return Array.isArray(v) ? v.join(", ") : typeof v === "string" ? v : "";
}

function paint(doc: jsPDF) {
  doc.setFillColor(...COLORS.background);
  doc.rect(0, 0, PAGE.w, PAGE.h, "F");
}

function header(doc: jsPDF, title: string, subtitle: string) {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(26);
  doc.setTextColor(...COLORS.charcoal);
  doc.text("STRAND", MARGIN, 24, { charSpace: 1.2 });

  doc.setFontSize(8);
  doc.setTextColor(...COLORS.gold);
  doc.text(title.toUpperCase(), PAGE.w - MARGIN, 24, { align: "right", charSpace: 0.5 });

  doc.setDrawColor(...COLORS.gold);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, 34, PAGE.w - MARGIN, 34);

  doc.setFontSize(11);
  doc.setTextColor(...COLORS.charcoal);
  doc.text(subtitle, MARGIN, 43);
}

function footer(doc: jsPDF, page: number, totalPages: number) {
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.2);
  doc.line(MARGIN, PAGE.h - 16, PAGE.w - MARGIN, PAGE.h - 16);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text("Generated by STRAND", MARGIN, PAGE.h - 10);
  doc.text(`Page ${page} of ${totalPages}`, PAGE.w - MARGIN, PAGE.h - 10, { align: "right" });
}

function ensureSpace(doc: jsPDF, y: number, needed: number) {
  if (y + needed <= PAGE.h - 24) return y;
  doc.addPage();
  paint(doc);
  header(doc, "Profile Export", "Your profile summary");
  return 50;
}

function section(doc: jsPDF, y: number, label: string, tone: [number, number, number] = COLORS.gold) {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...tone);
  doc.text(label.toUpperCase(), MARGIN, y);
  doc.setDrawColor(...tone);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y + 1.6, MARGIN + 16, y + 1.6);
  return y + 6;
}

function row(doc: jsPDF, y: number, label: string, value: string, tone: [number, number, number] = COLORS.charcoal) {
  const lines = doc.splitTextToSize(value, CONTENT_W - 48);
  const rowH = Math.max(13, 8 + lines.length * 4.2);
  doc.setFillColor(...COLORS.card);
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.15);
  doc.roundedRect(MARGIN, y, CONTENT_W, rowH, 1.5, 1.5, "FD");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text(label, MARGIN + 5, y + 5.5);

  doc.setFontSize(10);
  doc.setTextColor(...tone);
  doc.text(lines, MARGIN + 36, y + 5.5);

  return y + rowH + 3;
}

export function generateProfilePdf(input: ProfilePdfInput) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  paint(doc);
  header(doc, "Profile Export", `${input.displayName || "STRAND Member"} · ${new Date().toLocaleDateString()}`);

  let y = 52;

  y = section(doc, y, "Basic details");
  y = row(doc, y, "Name", input.displayName || "STRAND Member");
  if (input.age) y = row(doc, y, "Age", input.age);
  if (input.postcode) y = row(doc, y, "Postcode", input.postcode);
  if (input.waterHardness) y = row(doc, y, "Water", input.waterHardness);

  const diameter = toText(input.hair.diameter);
  const porosity = toText(input.hair.porosity);
  const density = toText(input.hair.density);
  const scalp = toText(input.hair.scalp);
  const diagnosed = input.hair.diagnosed?.join(", ") || "";

  const hasHair = !!(diameter || porosity || density || scalp || diagnosed);
  y = ensureSpace(doc, y, hasHair ? 28 : 18);
  y = section(doc, y, "Hair profile");
  if (!hasHair) {
    y = row(doc, y, "Status", "No hair profile details yet", COLORS.muted);
  } else {
    if (diameter) y = row(doc, y, "Strand diameter", diameter);
    if (porosity) y = row(doc, y, "Porosity", porosity, porosity.toLowerCase().includes("high") ? COLORS.warn : COLORS.charcoal);
    if (density) y = row(doc, y, "Density", density);
    if (scalp) y = row(doc, y, "Scalp condition", scalp, /dry|oily/i.test(scalp) ? COLORS.warn : COLORS.charcoal);
    if (diagnosed) y = row(doc, y, "Diagnosed", diagnosed, COLORS.warn);
  }

  y = ensureSpace(doc, y, 24);
  y = section(doc, y, "Blood summary", input.flaggedBlood.length > 0 ? COLORS.warn : COLORS.good);
  if (input.flaggedBlood.length > 0) {
    for (const b of input.flaggedBlood) {
      y = ensureSpace(doc, y, 18);
      y = row(doc, y, b.marker, `${b.value} ${b.unit} — ${b.status === "low" ? "Low" : "High"}`, COLORS.warn);
    }
  } else if (input.hasAnyBloodValues) {
    y = row(doc, y, "Status", "All blood markers in normal range", COLORS.good);
  } else {
    y = row(doc, y, "Status", "No blood results added yet", COLORS.muted);
  }

  y = ensureSpace(doc, y, 24);
  y = section(doc, y, "Medications");
  if (input.medications.length > 0) {
    y = row(doc, y, "Current", input.medications.join(", "));
  } else {
    y = row(doc, y, "Current", "No medications listed", COLORS.muted);
  }

  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    footer(doc, p, totalPages);
  }

  const safeName = (input.displayName || "client").replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "") || "client";
  const fileName = `STRAND-profile-${safeName}-${new Date().toISOString().slice(0, 10)}.pdf`;
  return { blob: doc.output("blob"), fileName };
}
