project_id = "wibimeglifveruvtvaxe"

[functions.journal-encouragement]
verify_jwt = false

[functions.pro-stripe-webhook]
verify_jwt = false

[functions.consumer-stripe-webhook]
verify_jwt = false

[functions.notify-admin-application]
verify_jwt = false

[functions.brand-stripe-webhook]
verify_jwt = false
