// PACED RE-ANALYSIS BACKFILL
//
// Re-runs the fixed, exposure-gated `ingredient-analysis` (Path 1 — the single
// source of truth) over every saved product so old rows stop carrying copy
// generated by the retired paths, and so `user_products` picks up the corrected
// summary/score/flags.
//
// Safety rails (see the background-jobs contract):
//   • bounded work per run (`limit`, default 6 items);
//   • single-flight lease in `ai_backfill_state.lease_until`;
//   • idempotent progress — each row is marked `done`/`failed` as it finishes;
//   • circuit breaker — a 402/403 from the gateway pauses the whole job, a
//     burst of 429s parks it until the next scheduled run;
//   • paused-state guard at the entry point, with a single probe item per run
//     so an out-of-band recovery (credits topped up) resumes the job.
//
// Invoked by pg_cron. Admins can also poke it manually with `{ "limit": n }`.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.95.0";
import { corsHeaders } from "https://esm.sh/@supabase/supabase-js@2.95.0/cors";

const JOB = "product_analysis_backfill";
const LEASE_MINUTES = 2; // matches the 2-minute cron cadence
const DEFAULT_LIMIT = 4;
const MAX_LIMIT = 25;
const MAX_ATTEMPTS = 3;
const GAP_MS = 800; // cooldown between items — keeps us under the rate limit
// The platform kills an invocation after 150s idle, so a run must finish well
// inside that: short, frequent runs beat long ones that get cut mid-item.
const RUN_BUDGET_MS = 110_000;
const ITEM_TIMEOUT_MS = 60_000; // a hung analysis can't eat the whole run
const STALE_RUNNING_MINUTES = 5; // requeue rows a dead run left in flight

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

interface QueueRow {
  id: string;
  user_id: string;
  user_product_id: string;
  product_key: string | null;
  attempts: number;
}

interface ProductRow {
  id: string;
  product_key: string | null;
  name: string | null;
  brand: string | null;
  category: string | null;
  ingredients: string[] | null;
  application_area: string | null;
  leave_on: boolean | null;
  usage_instructions: string | null;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  const url = Deno.env.get("SUPABASE_URL") ?? "";
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
  const admin = createClient(url, serviceKey, { auth: { persistSession: false } });

  let body: { limit?: number; resume?: boolean; single_user_product_id?: string } = {};
  try {
    body = (await req.json()) as typeof body;
  } catch {
    body = {};
  }
  const limit = Math.min(Math.max(Number(body.limit) || DEFAULT_LIMIT, 1), MAX_LIMIT);
  // SINGLE-ITEM OVERRIDE. Re-runs exactly ONE saved product, ignoring the
  // pause guard and the rest of the queue, and never clears the pause flag.
  // Used to prove a specific product's analysis without resuming the job.
  const singleId = typeof body.single_user_product_id === "string" && body.single_user_product_id
    ? body.single_user_product_id
    : null;

  // ── Job state: pause guard + single-flight lease ─────────────────────────
  const { data: stateRow } = await admin
    .from("ai_backfill_state")
    .select("paused, pause_reason, lease_until")
    .eq("job", JOB)
    .maybeSingle();
  const state = stateRow as
    | { paused: boolean | null; pause_reason: string | null; lease_until: string | null }
    | null;

  if (body.resume) {
    await admin
      .from("ai_backfill_state")
      .update({ paused: false, pause_reason: null, lease_until: null })
      .eq("job", JOB);
  }

  const paused = !body.resume && !singleId && !!state?.paused;
  // A GATEWAY pause (402/403) self-heals out of band, so it still runs exactly
  // ONE probe item per run: a denied probe spends no credits and keeps the
  // pause, a successful one clears it. A pause set by hand is a HARD STOP —
  // no probe, no items, nothing until someone resumes it explicitly.
  const gatewayPause = /^gateway /i.test(state?.pause_reason ?? "");
  if (paused && !gatewayPause) {
    return json({ skipped: "job paused", pause_reason: state?.pause_reason ?? null, paused: true });
  }
  const runLimit = singleId ? 1 : paused ? 1 : limit;



  const now = Date.now();
  const leaseHeld = !singleId && state?.lease_until && new Date(state.lease_until).getTime() > now;
  if (leaseHeld) {
    return json({ skipped: "another run holds the lease", lease_until: state!.lease_until });
  }


  const leaseUntil = new Date(now + LEASE_MINUTES * 60_000).toISOString();
  await admin
    .from("ai_backfill_state")
    .update({ lease_until: leaseUntil, last_run_at: new Date(now).toISOString() })
    .eq("job", JOB);

  const releaseLease = (note: string) =>
    admin.from("ai_backfill_state").update({ lease_until: null, note }).eq("job", JOB);

  const pauseJob = (reason: string) =>
    admin
      .from("ai_backfill_state")
      .update({ paused: true, pause_reason: reason, lease_until: null, note: reason })
      .eq("job", JOB);

  // Rows a dead run left marked in-flight go back on the queue — their attempt
  // was already counted, so this can't loop forever.
  if (!singleId) {
    await admin
      .from("product_analysis_backfill")
      .update({ status: "pending", last_error: "requeued after stalled run" })
      .eq("status", "running")
      .lt("updated_at", new Date(now - STALE_RUNNING_MINUTES * 60_000).toISOString());
  }

  // Single-item override: reset (or create) just this product's queue row so
  // the normal claim below picks it and nothing else.
  if (singleId) {
    const { data: p } = await admin
      .from("user_products")
      .select("id, user_id, product_key")
      .eq("id", singleId)
      .maybeSingle();
    if (!p) return json({ error: "product not found" }, 404);
    const prod = p as { id: string; user_id: string; product_key: string | null };
    const { data: existingQ } = await admin
      .from("product_analysis_backfill")
      .select("id")
      .eq("user_product_id", singleId)
      .maybeSingle();
    if (existingQ) {
      await admin
        .from("product_analysis_backfill")
        .update({ status: "pending", attempts: 0, last_error: null, processed_at: null })
        .eq("id", (existingQ as { id: string }).id);
    } else {
      await admin.from("product_analysis_backfill").insert({
        user_id: prod.user_id,
        user_product_id: prod.id,
        product_key: prod.product_key,
        status: "pending",
        attempts: 0,
      });
    }
  }

  // ── Claim a bounded batch ────────────────────────────────────────────────
  let claimQuery = admin
    .from("product_analysis_backfill")
    .select("id, user_id, user_product_id, product_key, attempts")
    .eq("status", "pending")
    .lt("attempts", MAX_ATTEMPTS);
  if (singleId) claimQuery = claimQuery.eq("user_product_id", singleId);
  const { data: queued, error: queueErr } = await claimQuery
    .order("created_at", { ascending: true })
    .limit(runLimit);


  if (queueErr) {
    await releaseLease(`queue read failed: ${queueErr.message}`);
    return json({ error: queueErr.message }, 500);
  }

  const rows = (queued ?? []) as unknown as QueueRow[];
  if (rows.length === 0) {
    await releaseLease("queue empty");
    return json({ processed: 0, remaining: 0, paused, done: true });
  }

  let processed = 0;
  let failed = 0;
  let rateLimited = 0;
  let breaker: string | null = null;

  for (const row of rows) {
    // Never overrun into the next scheduled tick — leftovers stay pending.
    if (Date.now() - now > RUN_BUDGET_MS) break;
    // Mark in-flight so a crash can't hide the attempt.
    await admin
      .from("product_analysis_backfill")
      .update({ status: "running", attempts: row.attempts + 1 })
      .eq("id", row.id);

    const { data: prodData } = await admin
      .from("user_products")
      .select(
        "id, product_key, name, brand, category, ingredients, application_area, leave_on, usage_instructions",
      )
      .eq("id", row.user_product_id)
      .maybeSingle();
    const product = prodData as unknown as ProductRow | null;

    if (!product || !Array.isArray(product.ingredients) || product.ingredients.length < 2) {
      await admin
        .from("product_analysis_backfill")
        .update({
          status: "skipped",
          processed_at: new Date().toISOString(),
          last_error: "no usable ingredient list",
        })
        .eq("id", row.id);
      continue;
    }

    // Durable profile signals the analysis weighs. Read server-side so the job
    // needs no client context payload.
    const [{ data: hair }, { data: goals }, { data: style }, { data: profile }] = await Promise.all([
      admin.from("user_hair_profile").select("*").eq("user_id", row.user_id).maybeSingle(),
      admin
        .from("user_goals")
        .select("kind, title, challenges, target_text, status")
        .eq("user_id", row.user_id)
        .limit(6),
      admin
        .from("user_style_profile")
        .select("default_style, planned_next_style")
        .eq("user_id", row.user_id)
        .maybeSingle(),
      admin
        .from("profiles")
        .select("tips_level")
        .eq("user_id", row.user_id)
        .maybeSingle(),
    ]);

    const payload = {
      backfillUserId: row.user_id,
      // The explicit single-product repair path must reuse a valid cache when
      // one exists (including a safe higher→lower guidance-level downshift).
      // Bulk backfill remains forceful because its purpose is regeneration.
      force: !singleId,
      productKey: product.product_key ?? row.product_key ?? product.id,
      productName: product.name ?? "Saved product",
      productBrand: product.brand ?? "",
      ingredients: product.ingredients,
      category: product.category,
      applicationArea: product.application_area,
      leaveOn: product.leave_on,
      usageInstructions: product.usage_instructions,
      hairProfile: (hair ?? {}) as Record<string, unknown>,
      goals: (goals ?? []) as Array<Record<string, unknown>>,
      currentStyle: (style ?? null) as Record<string, unknown> | null,
      context: {
        hairProfile: (hair ?? {}) as Record<string, unknown>,
        goals: (goals ?? []) as Array<Record<string, unknown>>,
        currentStyle: (style ?? null) as Record<string, unknown> | null,
        // Cache identity includes guidance level. Omitting this silently used
        // the L2 default and made L1/L3 members miss the generated row forever.
        tipsLevel: (profile as { tips_level?: number | null } | null)?.tips_level ?? 2,
      },
    };

    let status = 0;
    let errText = "";
    try {
      const res = await fetch(`${url}/functions/v1/ingredient-analysis`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${serviceKey}`,
          apikey: serviceKey,
        },
        body: JSON.stringify(payload),
        // A single hung analysis used to swallow the whole run.
        signal: AbortSignal.timeout(ITEM_TIMEOUT_MS),
      });
      status = res.status;
      if (!res.ok) errText = (await res.text()).slice(0, 500);
    } catch (e) {
      errText = e instanceof Error ? e.message : String(e);
    }

    if (status === 402 || status === 403) {
      // Terminal denial — halt the whole job, not just this item.
      breaker = `gateway ${status}: ${errText}`;
      await admin
        .from("product_analysis_backfill")
        .update({ status: "pending", last_error: breaker })
        .eq("id", row.id);
      break;
    }

    if (status === 429) {
      rateLimited += 1;
      await admin
        .from("product_analysis_backfill")
        .update({ status: "pending", last_error: `rate limited: ${errText}` })
        .eq("id", row.id);
      if (rateLimited >= 2) break; // park until the next scheduled run
      await sleep(5000);
      continue;
    }

    if (status >= 200 && status < 300) {
      processed += 1;
      await admin
        .from("product_analysis_backfill")
        .update({ status: "done", processed_at: new Date().toISOString(), last_error: null })
        .eq("id", row.id);
      if (paused) {
        // Successful probe — the block cleared out of band.
        await admin
          .from("ai_backfill_state")
          .update({ paused: false, pause_reason: null })
          .eq("job", JOB);
      }
    } else {
      failed += 1;
      const terminal = row.attempts + 1 >= MAX_ATTEMPTS;
      await admin
        .from("product_analysis_backfill")
        .update({
          status: terminal ? "failed" : "pending",
          last_error: `${status || "network"}: ${errText}`,
          processed_at: terminal ? new Date().toISOString() : null,
        })
        .eq("id", row.id);
    }

    await sleep(GAP_MS);
  }

  if (breaker) {
    await pauseJob(breaker);
  } else {
    await releaseLease(
      rateLimited > 0
        ? `parked on rate limit after ${processed} item(s)`
        : `ran ${processed} ok, ${failed} failed`,
    );
  }

  const { count: remaining } = await admin
    .from("product_analysis_backfill")
    .select("id", { count: "exact", head: true })
    .eq("status", "pending");

  return json({
    processed,
    failed,
    rate_limited: rateLimited,
    remaining: remaining ?? 0,
    paused: Boolean(breaker) || (paused && processed === 0),
    pause_reason: breaker ?? (paused ? state?.pause_reason ?? null : null),
  });
});
