import { writeFileSync } from "node:fs";
// Generates a STRAND-branded PDF report of the user's auto-derived ingredient
// lists (avoid + favourites). Uses jsPDF directly — no DOM rasterization — so
// the output is sharp, selectable text, and small file size.
//
// Branding cues:
//   - Warm sand page background (#F2E8D9)
//   - Gold accent rule + section labels (#C49A3C)
//   - Charcoal body text (#2C2416)
//   - Serif display (Times) for headings, Helvetica for body — closest match
//     to Playfair Display + Jost using jsPDF's built-in font set, and avoids
//     shipping a font file just for this report.
import { jsPDF } from "jspdf";
import type { IngredientListRow } from "./types";

interface ReportInput {
  userName: string;
  avoid: IngredientListRow[];
  favourites: IngredientListRow[];
}

// HSL → RGB tuple. STRAND tokens are HSL so we mirror them here for accuracy.
const COLORS = {
  background: [242, 232, 217] as [number, number, number], // #F2E8D9
  card: [253, 248, 242] as [number, number, number], // #FDF8F2
  border: [221, 208, 184] as [number, number, number], // #DDD0B8
  charcoal: [44, 36, 22] as [number, number, number], // #2C2416
  muted: [122, 106, 84] as [number, number, number], // #7A6A54
  gold: [196, 154, 60] as [number, number, number], // #C49A3C
  warn: [184, 112, 32] as [number, number, number], // #B87020
  good: [90, 138, 90] as [number, number, number], // #5A8A5A
};

const PAGE = { w: 210, h: 297 }; // A4 portrait, mm
const MARGIN = 18;
const CONTENT_W = PAGE.w - MARGIN * 2;

function paintBackground(doc: jsPDF) {
  doc.setFillColor(...COLORS.background);
  doc.rect(0, 0, PAGE.w, PAGE.h, "F");
}

function drawHeader(doc: jsPDF) {
  // Wordmark
  doc.setFont("times", "normal");
  doc.setFontSize(28);
  doc.setTextColor(...COLORS.charcoal);
  doc.text("STRAND", MARGIN, 24);

  // Tiny tag under the mark
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.muted);
  doc.text("HAIR · INGREDIENTS · CARE", MARGIN, 29);

  // Right-aligned report label
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.gold);
  const label = "INGREDIENT REPORT";
  doc.text(label, PAGE.w - MARGIN, 24, { align: "right" });

  // Gold rule under header
  doc.setDrawColor(...COLORS.gold);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, 34, PAGE.w - MARGIN, 34);
}

function drawFooter(doc: jsPDF, page: number, totalPages: number) {
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.2);
  doc.line(MARGIN, PAGE.h - 16, PAGE.w - MARGIN, PAGE.h - 16);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text("Generated by STRAND", MARGIN, PAGE.h - 10);
  doc.text(
    `Page ${page} of ${totalPages}`,
    PAGE.w - MARGIN,
    PAGE.h - 10,
    { align: "right" },
  );
}

/** Make sure there's room for `needed` mm before the footer; otherwise break. */
function ensureSpace(
  doc: jsPDF,
  cursorY: number,
  needed: number,
  onNewPage: () => number,
): number {
  if (cursorY + needed > PAGE.h - 22) {
    doc.addPage();
    paintBackground(doc);
    drawHeader(doc);
    return onNewPage();
  }
  return cursorY;
}

function drawIntro(
  doc: jsPDF,
  userName: string,
  avoidCount: number,
  favCount: number,
): number {
  let y = 46;

  doc.setFont("times", "normal");
  doc.setFontSize(20);
  doc.setTextColor(...COLORS.charcoal);
  doc.text("Your Ingredient Profile", MARGIN, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.muted);
  const today = new Date().toLocaleDateString(undefined, {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  doc.text(`Prepared for ${userName} · ${today}`, MARGIN, y);
  y += 9;

  // Intro paragraph
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.charcoal);
  const intro =
    "This report summarises the ingredients automatically flagged from this user's product ratings inside the STRAND app. Use it as a starting point for consultations — these patterns reflect real-world tolerance and preference, not clinical diagnosis.";
  const introLines = doc.splitTextToSize(intro, CONTENT_W);
  doc.text(introLines, MARGIN, y);
  y += introLines.length * 4.6 + 4;

  // Summary chip row
  const chipY = y;
  const chipH = 18;
  const chipW = (CONTENT_W - 6) / 2;

  // Avoid chip
  doc.setFillColor(...COLORS.card);
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.2);
  doc.roundedRect(MARGIN, chipY, chipW, chipH, 2, 2, "FD");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.warn);
  doc.text("AVOID", MARGIN + 5, chipY + 6);
  doc.setFont("times", "normal");
  doc.setFontSize(18);
  doc.setTextColor(...COLORS.charcoal);
  doc.text(String(avoidCount), MARGIN + 5, chipY + 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  doc.text(
    avoidCount === 1 ? "ingredient flagged" : "ingredients flagged",
    MARGIN + 16,
    chipY + 14,
  );

  // Favourites chip
  const favX = MARGIN + chipW + 6;
  doc.setFillColor(...COLORS.card);
  doc.setDrawColor(...COLORS.border);
  doc.roundedRect(favX, chipY, chipW, chipH, 2, 2, "FD");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.good);
  doc.text("FAVOURITES", favX + 5, chipY + 6);
  doc.setFont("times", "normal");
  doc.setFontSize(18);
  doc.setTextColor(...COLORS.charcoal);
  doc.text(String(favCount), favX + 5, chipY + 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  doc.text(
    favCount === 1 ? "ingredient loved" : "ingredients loved",
    favX + 16,
    chipY + 14,
  );

  return chipY + chipH + 10;
}

function drawSectionHeading(doc: jsPDF, y: number, label: string, accent: [number, number, number]) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...accent);
  doc.text(label.toUpperCase(), MARGIN, y);

  doc.setDrawColor(...accent);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y + 1.6, MARGIN + 14, y + 1.6);

  return y + 6;
}

function drawIngredientRow(
  doc: jsPDF,
  y: number,
  row: IngredientListRow,
  accent: [number, number, number],
): number {
  const rowH = 13;

  // Card background
  doc.setFillColor(...COLORS.card);
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.15);
  doc.roundedRect(MARGIN, y, CONTENT_W, rowH, 1.5, 1.5, "FD");

  // Status dot
  doc.setFillColor(...accent);
  doc.circle(MARGIN + 4, y + rowH / 2, 1.1, "F");

  // Ingredient name
  doc.setFont("times", "normal");
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.charcoal);
  doc.text(row.ingredient, MARGIN + 8, y + 5.6);

  // Reason
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text(row.reason, MARGIN + 8, y + 10);

  // Right-side count
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...accent);
  doc.text(
    `${row.product_count}×`,
    PAGE.w - MARGIN - 4,
    y + 8,
    { align: "right" },
  );

  return y + rowH + 3;
}

function drawEmptyState(doc: jsPDF, y: number, message: string): number {
  doc.setFillColor(...COLORS.card);
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.15);
  doc.roundedRect(MARGIN, y, CONTENT_W, 14, 1.5, 1.5, "FD");
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  doc.text(message, MARGIN + 5, y + 8.5);
  return y + 14 + 3;
}

export function generateIngredientReportPdf(input: ReportInput) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  paintBackground(doc);
  drawHeader(doc);
  let y = drawIntro(doc, input.userName, input.avoid.length, input.favourites.length);

  const continuationY = () => 46;

  // AVOID section
  y = ensureSpace(doc, y, 18, continuationY);
  y = drawSectionHeading(doc, y, "Ingredients to avoid", COLORS.warn);

  if (input.avoid.length === 0) {
    y = drawEmptyState(
      doc,
      y,
      "No ingredients flagged yet — rate two or more products 1–2★ to populate.",
    );
  } else {
    for (const row of input.avoid) {
      y = ensureSpace(doc, y, 16, continuationY);
      y = drawIngredientRow(doc, y, row, COLORS.warn);
    }
  }

  y += 4;

  // FAVOURITES section
  y = ensureSpace(doc, y, 18, continuationY);
  y = drawSectionHeading(doc, y, "Favourite ingredients", COLORS.good);

  if (input.favourites.length === 0) {
    y = drawEmptyState(
      doc,
      y,
      "No favourites yet — rate two or more products 4–5★ to populate.",
    );
  } else {
    for (const row of input.favourites) {
      y = ensureSpace(doc, y, 16, continuationY);
      y = drawIngredientRow(doc, y, row, COLORS.good);
    }
  }

  // Footers across all pages
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    drawFooter(doc, p, totalPages);
  }

  const safeName = input.userName.replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "") || "client";
  const dateStamp = new Date().toISOString().slice(0, 10);
  writeFileSync("/tmp/pdfqa/" + (`STRAND-ingredient-report-${safeName}-${dateStamp}.pdf`), Buffer.from(doc.output("arraybuffer"))); console.log("wrote");
}
