import { useEffect, useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import {
  useActiveBrandOffer,
  useAdViewTracker,
} from "@/hooks/useBrandOffers";
import { usePersonalisedOffersConsent } from "@/hooks/useAdTargeting";
import { useBrandProductGuidance } from "@/hooks/useBrandProductGuidance";
import { resolveBrandColours, tint } from "@/lib/brandColour";
import AiProgressBar from "@/components/AiProgressBar";

/**
 * SponsoredWashDayTipCard — the sponsored tip on the Wash Day screen.
 *
 * SCOPE: the disclosure label and the personalised next-wash-day tip. NOTHING
 * ELSE. No "Learn more", no offer-details dropdown, no discount code, no
 * "offer ends" line and no add-to-shelf block — every one of those lives in the
 * approved advert (`BrandOfferBanner`) that renders directly beneath this card,
 * and duplicating them showed the member the same code and product twice.
 *
 * The tip is an addition ON TOP of the advert, not a reformat of it.
 *
 * Brand colour is the ONLY deviation from the design system: a 7% tint of the
 * brand primary on the card surface, a full-strength left edge and a
 * brand-coloured "TRY THIS" label. Body text always uses the standard
 * foreground token. Colours come pre-extracted from `brand_profiles`; a
 * missing/failed extraction resolves to the STRAND gold token.
 *
 * The tip text is generated by STRAND (brand-product-guidance, manuscript
 * grounded with citation checks) from the member's own data — two sentences,
 * 45 words, enforced server-side. The brand supplies only the product; it can
 * never write or edit this text.
 */
const SLOT = "wash_day";

export interface SponsoredWashDayTipCardProps {
  /**
   * ADMIN PREVIEW. Renders the card for review without a personalised-offers
   * consent, without a delivery match, and — critically — WITHOUT logging any
   * `ad_events`, so a review never contaminates a brand's reported metrics.
   */
  preview?: boolean;
  /** Which offer to preview. Defaults to the most recent offer with a product. */
  previewOfferId?: string;
  /** Reports whether this card actually rendered. The wash day page uses it to
   *  suppress the educational tip ONLY when a sponsored tip is shown — a member
   *  without consent, or on a day with no wash day campaign, still gets their
   *  educational tip. */
  onRendered?: (rendered: boolean) => void;
}

const SponsoredWashDayTipCard = ({ preview = false, previewOfferId, onRendered }: SponsoredWashDayTipCardProps = {}) => {
  const { data: consented } = usePersonalisedOffersConsent();
  const { data: liveDelivery } = useActiveBrandOffer(SLOT, { enabled: !preview });

  // Preview source: an explicit offer, else the newest offer that has a
  // product attached — status-agnostic, because a campaign has to be
  // reviewable BEFORE it goes live.
  const { data: previewDelivery } = useQuery({
    queryKey: ["sponsored-tip-preview", previewOfferId ?? "latest"],
    enabled: preview,
    staleTime: 60_000,
    queryFn: async () => {
      let q = supabase
        .from("brand_offers")
        .select(
          "id, headline, body_copy, discount_code, external_url, ends_on, brand_user_id, brand_offer_products(position, created_at, brand_products(id, name, description, kind, tool_kind, ingredients, key_features, materials, image_urls, external_url))",
        )
        .order("created_at", { ascending: false })
        .order("position", { referencedTable: "brand_offer_products", ascending: true })
        .order("created_at", { referencedTable: "brand_offer_products", ascending: true })
        .limit(10);
      if (previewOfferId) q = q.eq("id", previewOfferId);
      const { data } = await q;
      const row = (data ?? []).find(
        (o) => (o as { brand_offer_products?: unknown[] }).brand_offer_products?.length,
      );
      if (!row) return null;
      // ONE PRODUCT PER ADVERT — the junction carries a single row.
      const products = ((row as { brand_offer_products?: Array<{ brand_products: unknown }> })
        .brand_offer_products ?? []).map((r) => r.brand_products);
      return { brand_offers: { ...row, brand_products: products }, was_matched: null, match_reason: null };
    },
  });
  const delivery = preview ? previewDelivery : liveDelivery;

  const offer = delivery?.brand_offers as
    | {
        id: string;
        headline: string | null;
        brand_user_id?: string | null;
        brand_products?: Array<{
          id: string;
          name: string;
          description?: string | null;
          kind?: string | null;
          tool_kind?: string | null;
          ingredients?: string[] | null;
          key_features?: string[] | null;
          materials?: string[] | null;
          image_urls?: string[] | null;
          external_url?: string | null;
        }> | null;
      }
    | undefined;
  // ONE PRODUCT PER ADVERT — enforced at submission, so this is the advertised
  // product, not a pick from a list.
  const product = offer?.brand_products?.[0] ?? null;
  const enabled = (preview || !!consented) && !!offer?.id && !!product;

  // Brand identity: name + the colours extracted once at logo upload.
  const { data: brand } = useQuery({
    queryKey: ["sponsored-tip-brand", offer?.brand_user_id],
    enabled: !!offer?.brand_user_id,
    staleTime: 5 * 60_000,
    queryFn: async () => {
      const { data } = await supabase
        .from("brand_profiles")
        .select(
          "brand_name, brand_colour_primary, brand_colour_secondary, brand_colour_on_primary",
        )
        .eq("user_id", offer!.brand_user_id!)
        .maybeSingle();
      return data ?? null;
    },
  });

  const colours = useMemo(
    () => resolveBrandColours(brand as Parameters<typeof resolveBrandColours>[0]),
    [brand],
  );
  const brandName = (brand as { brand_name?: string | null } | null)?.brand_name ?? null;

  // STRAND's own read of this product against this member's wash day.
  const { guidance, loading } = useBrandProductGuidance(
    enabled && product
      ? { ...product, brand: brandName, ingredients: product.ingredients ?? [] }
      : null,
    { enabled, surface: "wash_day" },
  );

  // No impression is logged in preview mode. `unit: "wash_day_tip"` keeps this
  // card's impressions separable from the advert's own `advert` events.
  const viewRef = useAdViewTracker(enabled && !preview ? offer!.id : undefined, SLOT as never, {
    was_matched: delivery?.was_matched ? true : null,
    match_reason: delivery?.match_reason ? { codes: delivery.match_reason } : null,
    unit: "wash_day_tip",
  });

  const rendering = enabled && !!offer && !!product;
  useEffect(() => {
    onRendered?.(rendering);
    return () => onRendered?.(false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [rendering]);

  if (!rendering || !offer || !product) return null;

  return (
    <section
      ref={viewRef}
      className="rounded-[14px] border overflow-hidden"
      style={{
        // 7% tint of the ORIGINAL extracted brand colour over the card surface
        // — the tint must look like the brand, so it never uses the darkened
        // text-safe accent. A whisper, not a flood.
        backgroundColor: tint(colours.primary, 0.07),
        borderColor: tint(colours.primary, 0.35),
        // Left edge accent: the extracted brand colour at full strength. No text
        // sits on it, so it stays exactly as the logo gave it.
        borderLeft: `3px solid ${colours.primary}`,
      }}
    >
      {preview && (
        <p className="px-4 pt-3 text-[10px] uppercase tracking-[0.16em] font-bold font-body text-foreground/60">
          Admin preview — not shown to members, nothing logged
        </p>
      )}
      <div className="p-4">
        {/* Disclosure — same prominence as the tip label, never small print. */}
        <div className="flex items-center justify-between gap-2">
          <p
            className="text-[10px] uppercase tracking-[0.18em] font-bold font-body"
            style={{ color: colours.accent }}
          >
            Sponsored Wash Day Tip
          </p>
          <span
            className="text-[9px] uppercase tracking-[0.16em] font-bold font-body rounded px-1.5 py-0.5"
            style={{ backgroundColor: colours.accent, color: colours.onAccent }}
          >
            Ad
          </span>
        </div>

        {/* The tip, and only the tip: one succinct personalised read beside the
            product's own thumbnail. Every control that used to sit below this
            block now lives in the advert beneath. */}
        <div className="mt-2.5 flex gap-2.5 rounded-[10px] bg-card/70 px-2.5 py-2">
          <div className="size-[58px] shrink-0 overflow-hidden rounded-xl border border-border bg-muted/40">
            {product.image_urls?.[0] ? (
              <img
                src={product.image_urls[0]}
                alt={product.name}
                loading="lazy"
                className="h-full w-full object-cover"
              />
            ) : (
              <div className="flex h-full w-full items-center justify-center font-display text-lg text-primary/50">
                ✦
              </div>
            )}
          </div>
          <p className="min-w-0 text-[11.5px] leading-[1.55] font-body text-foreground break-words">
            <span
              className="text-[9.5px] uppercase tracking-[0.18em] font-bold mr-1.5"
              style={{ color: colours.accent }}
            >
              Try this
            </span>
            {loading && !guidance ? (
              <span className="text-foreground/60">Working out how this fits your wash day…</span>

            ) : (
              guidance?.wash_day_tip || guidance?.fit_line || product.description || ""
            )}
          </p>
        </div>
      </div>
    </section>
  );
};

export default SponsoredWashDayTipCard;
