import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ChevronDown, ChevronUp, Loader2, Plus, Check, ExternalLink } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import {
  useActiveBrandOffer,
  useLogAdEvent,
  useAdViewTracker,
} from "@/hooks/useBrandOffers";
import { usePersonalisedOffersConsent } from "@/hooks/useAdTargeting";
import { useUserProducts } from "@/hooks/useUserProducts";
import { useBrandProductGuidance } from "@/hooks/useBrandProductGuidance";
import DiscountCodeChip from "@/components/DiscountCodeChip";
import { resolveBrandColours, tint } from "@/lib/brandColour";

/**
 * SponsoredWashDayTipCard — Card 2 on the Wash Day screen.
 *
 * Sits directly BENEATH the STRAND tip (Card 1) and never replaces or
 * suppresses it. Rendered only for members who granted `personalised_offers`;
 * with no consent, no live wash-day campaign, or no attached product it
 * renders nothing at all (no empty shell).
 *
 * Brand colour is the ONLY deviation from the design system, applied exactly
 * as specified: a 7% tint of the brand primary on the card surface, a
 * full-strength left edge, a brand-coloured "TRY THIS" label and a filled CTA.
 * Body text always uses the standard foreground token. Colours come
 * pre-extracted from `brand_profiles`; a missing/failed extraction resolves to
 * the STRAND gold token via `resolveBrandColours`.
 *
 * The guidance text is generated by STRAND (brand-product-guidance, manuscript
 * grounded with citation checks) from the member's own data. The brand supplies
 * only the product, offer copy, discount code and link — it can never write or
 * edit this text.
 */
const SLOT = "wash_day";

const formatEnds = (iso: string | null | undefined) => {
  if (!iso) return null;
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return null;
  return d.toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
};

export interface SponsoredWashDayTipCardProps {
  /**
   * ADMIN PREVIEW. Renders the card for review without a personalised-offers
   * consent, without a delivery match, and — critically — WITHOUT logging any
   * `ad_events`, so a review never contaminates a brand's reported metrics.
   */
  preview?: boolean;
  /** Which offer to preview. Defaults to the most recent offer with a product. */
  previewOfferId?: string;
  /** Reports whether this card actually rendered. The wash day page uses it to
   *  suppress the educational tip (Card 1) ONLY when a sponsored tip is shown —
   *  a member without consent, or on a day with no wash day campaign, still
   *  gets their educational tip. */
  onRendered?: (rendered: boolean) => void;
}

const SponsoredWashDayTipCard = ({ preview = false, previewOfferId, onRendered }: SponsoredWashDayTipCardProps = {}) => {
  const nav = useNavigate();
  const { user } = useAuth();
  const { data: consented } = usePersonalisedOffersConsent();
  const { data: liveDelivery } = useActiveBrandOffer(SLOT, { enabled: !preview });
  const logEvent = useLogAdEvent();

  // Preview source: an explicit offer, else the newest offer that has a
  // product attached — status-agnostic, because a campaign has to be
  // reviewable BEFORE it goes live.
  const { data: previewDelivery } = useQuery({
    queryKey: ["sponsored-tip-preview", previewOfferId ?? "latest"],
    enabled: preview,
    staleTime: 60_000,
    queryFn: async () => {
      let q = supabase
        .from("brand_offers")
        .select(
          "id, headline, body_copy, discount_code, external_url, ends_on, brand_user_id, brand_offer_products(position, created_at, brand_products(id, name, description, kind, tool_kind, ingredients, key_features, materials, image_urls, external_url))",
        )
        .order("created_at", { ascending: false })
        .order("position", { referencedTable: "brand_offer_products", ascending: true })
        .order("created_at", { referencedTable: "brand_offer_products", ascending: true })
        .limit(10);
      if (previewOfferId) q = q.eq("id", previewOfferId);
      const { data } = await q;
      const row = (data ?? []).find(
        (o) => (o as { brand_offer_products?: unknown[] }).brand_offer_products?.length,
      );
      if (!row) return null;
      // Preview shows what members see: the FIRST attached product by
      // `position`, never a list.
      const products = ((row as { brand_offer_products?: Array<{ brand_products: unknown }> })
        .brand_offer_products ?? []).map((r) => r.brand_products).slice(0, 1);
      return { brand_offers: { ...row, brand_products: products }, was_matched: null, match_reason: null };
    },
  });
  const delivery = preview ? previewDelivery : liveDelivery;
  const { allProducts, upsert } = useUserProducts();
  const [expanded, setExpanded] = useState(false);
  const [busy, setBusy] = useState(false);

  const offer = delivery?.brand_offers as
    | {
        id: string;
        headline: string | null;
        body_copy?: string | null;
        discount_code?: string | null;
        external_url?: string | null;
        ends_on?: string | null;
        brand_user_id?: string | null;
        brand_products?: Array<{
          id: string;
          name: string;
          description?: string | null;
          kind?: string | null;
          tool_kind?: string | null;
          ingredients?: string[] | null;
          key_features?: string[] | null;
          materials?: string[] | null;
          image_urls?: string[] | null;
          external_url?: string | null;
        }> | null;
      }
    | undefined;
  // EXACTLY ONE PRODUCT. An offer may have several attached; this card promotes
  // only the first by `position` (then earliest created) — never a list, never
  // a carousel. The brand controls which one by ordering their shelf.
  const product = offer?.brand_products?.[0] ?? null;
  const enabled = (preview || !!consented) && !!offer?.id && !!product;

  // Brand identity: name + the colours extracted once at logo upload.
  const { data: brand } = useQuery({
    queryKey: ["sponsored-tip-brand", offer?.brand_user_id],
    enabled: !!offer?.brand_user_id,
    staleTime: 5 * 60_000,
    queryFn: async () => {
      const { data } = await supabase
        .from("brand_profiles")
        .select(
          "brand_name, brand_colour_primary, brand_colour_secondary, brand_colour_on_primary",
        )
        .eq("user_id", offer!.brand_user_id!)
        .maybeSingle();
      return data ?? null;
    },
  });

  const colours = useMemo(
    () => resolveBrandColours(brand as Parameters<typeof resolveBrandColours>[0]),
    [brand],
  );
  const brandName = (brand as { brand_name?: string | null } | null)?.brand_name ?? null;

  // STRAND's own read of this product against this member's wash day.
  const { guidance, loading } = useBrandProductGuidance(
    enabled && product
      ? { ...product, brand: brandName, ingredients: product.ingredients ?? [] }
      : null,
    { enabled, surface: "wash_day" },
  );

  // No impression is logged in preview mode.
  const viewRef = useAdViewTracker(enabled && !preview ? offer!.id : undefined, SLOT as never, {
    was_matched: delivery?.was_matched ? true : null,
    match_reason: delivery?.match_reason ? { codes: delivery.match_reason } : null,
    // Separate attribution unit: tip impressions never merge with advert ones.
    unit: "wash_day_tip",
  });

  const shelfRow = useMemo(() => {
    if (!product) return null;
    return (
      allProducts.find(
        (row) =>
          row.linked_brand_product_id === product.id ||
          row.product_key === `brand-offer:${product.id}` ||
          (row.name.trim().toLowerCase() === product.name.trim().toLowerCase() &&
            (row.brand ?? "").trim().toLowerCase() === (brandName ?? "").trim().toLowerCase()),
      ) ?? null
    );
  }, [allProducts, product, brandName]);
  const onShelf = !!shelfRow?.on_shelf;

  useEffect(() => {
    setExpanded(false);
  }, [offer?.id]);

  const rendering = enabled && !!offer && !!product;
  useEffect(() => {
    onRendered?.(rendering);
    return () => onRendered?.(false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [rendering]);

  if (!rendering || !offer || !product) return null;

  /** Every ad_event goes through here so preview mode can silence all of them. */
  const track = (event: Parameters<typeof logEvent.mutate>[0]) => {
    if (preview) return;
    // Every event from this card is tagged `wash_day_tip` so a tap on the tip is
    // never indistinguishable from a tap on the advert beneath it.
    logEvent.mutate({ ...event, unit: "wash_day_tip" });
  };

  const toggle = () => {
    setExpanded((v) => {
      if (!v) track({ offer_id: offer.id, brand_product_id: product.id, slot: SLOT, event_type: "expand" });
      return !v;
    });
  };

  const openProduct = () => {
    track({ offer_id: offer.id, brand_product_id: product.id, slot: SLOT, event_type: "link_click" });
    // Existing rule: a member who already owns it goes to their own shelf item,
    // never to a brand copy of the same product.
    if (onShelf && shelfRow) nav(`/products/profile/${shelfRow.id}`);
    else nav(`/offers/${offer.id}/product/${product.id}?slot=${SLOT}`);
  };

  const addToShelf = async () => {
    if (!user) return;
    setBusy(true);
    try {
      const row = await upsert({
        product_key: shelfRow?.product_key ?? `brand-offer:${product.id}`,
        name: product.name,
        brand: brandName,
        ingredients: (product.ingredients ?? []) as string[],
        image_url: product.image_urls?.[0] ?? null,
        linked_brand_offer_id: offer.id,
        linked_brand_product_id: product.id,
        on_shelf: true,
        on_wishlist: false,
      });
      if (!row) throw new Error("Could not add to your shelf");
      track({ offer_id: offer.id, brand_product_id: product.id, slot: SLOT, event_type: "shelf_add" });
      toast.success("Added to your shelf");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Could not add to your shelf");
    } finally {
      setBusy(false);
    }
  };

  const endsOn = formatEnds(offer.ends_on);

  return (
    <section
      ref={viewRef}
      className="rounded-[14px] border overflow-hidden"
      style={{
        // 7% tint of the ORIGINAL extracted brand colour over the card surface
        // — the tint must look like the brand, so it never uses the darkened
        // text-safe accent. A whisper, not a flood.
        backgroundColor: tint(colours.primary, 0.07),
        borderColor: tint(colours.primary, 0.35),
        // Left edge accent: the extracted brand colour at full strength. No text
        // sits on it, so it stays exactly as the logo gave it.
        borderLeft: `3px solid ${colours.primary}`,
      }}
    >
      {preview && (
        <p className="px-4 pt-3 text-[10px] uppercase tracking-[0.16em] font-bold font-body text-foreground/60">
          Admin preview — not shown to members, nothing logged
        </p>
      )}
      <div className="p-4">
        {/* Disclosure — same prominence as the TRY THIS label, never small print. */}
        <div className="flex items-center justify-between gap-2">
          <p
            className="text-[10px] uppercase tracking-[0.18em] font-bold font-body"
            style={{ color: colours.accent }}
          >
            Sponsored Wash Day Tip
          </p>
          <span
            className="text-[9px] uppercase tracking-[0.16em] font-bold font-body rounded px-1.5 py-0.5"
            style={{ backgroundColor: colours.accent, color: colours.onAccent }}
          >
            Ad
          </span>
        </div>

        <h3 className="font-display text-[15.5px] leading-snug mt-1.5 text-foreground break-words">
          {guidance?.headline || offer.headline || product.name}
        </h3>

        {/* TRY THIS — one succinct personalised read (max two sentences, 45
            words, enforced server-side), beside the product's own thumbnail.
            The thumbnail treatment is the brand shelf card one, unchanged. */}
        <div className="mt-2.5 flex gap-2.5 rounded-[10px] bg-card/70 px-2.5 py-2">
          <div className="size-[58px] shrink-0 overflow-hidden rounded-xl border border-border bg-muted/40">
            {product.image_urls?.[0] ? (
              <img
                src={product.image_urls[0]}
                alt={product.name}
                loading="lazy"
                className="h-full w-full object-cover"
              />
            ) : (
              <div className="flex h-full w-full items-center justify-center font-display text-lg text-primary/50">
                ✦
              </div>
            )}
          </div>
          <p className="min-w-0 text-[11.5px] leading-[1.55] font-body text-foreground break-words">
            <span
              className="text-[9.5px] uppercase tracking-[0.18em] font-bold mr-1.5"
              style={{ color: colours.accent }}
            >
              Try this
            </span>
            {loading && !guidance ? (
              <span className="text-foreground/60">Working out how this fits your wash day…</span>
            ) : (
              guidance?.wash_day_tip || guidance?.fit_line || product.description || ""
            )}
          </p>
        </div>


        <button
          type="button"
          onClick={openProduct}
          className="mt-3 w-full min-h-[44px] rounded-full font-body font-semibold text-[12.5px] inline-flex items-center justify-center gap-1.5"
          style={{ backgroundColor: colours.accent, color: colours.onAccent }}
        >
          Learn more
          <ExternalLink className="size-3.5" aria-hidden />
        </button>

        {/* Offer details — collapsed by default. */}
        <button
          type="button"
          onClick={toggle}
          aria-expanded={expanded}
          className="mt-2 w-full min-h-[40px] inline-flex items-center justify-center gap-1 text-[11.5px] font-body font-semibold"
          style={{ color: colours.accent }}
        >
          {expanded ? "Hide offer details" : "See offer details"}
          {expanded ? <ChevronUp className="size-3.5" /> : <ChevronDown className="size-3.5" />}
        </button>

        {expanded && (
          <div className="mt-1 space-y-2.5">
            {offer.body_copy && (
              <p className="text-[11.5px] leading-[1.55] font-body text-foreground/80 break-words">
                {offer.body_copy}
              </p>
            )}
            {offer.discount_code && (
              <DiscountCodeChip
                code={offer.discount_code}
                variant="block"
                onCopy={() =>
                  track({
                    offer_id: offer.id,
                    brand_product_id: product.id,
                    slot: SLOT,
                    event_type: "code_copy",
                  })
                }
              />
            )}
            {endsOn && (
              <p className="text-[11px] font-body text-foreground/70">
                Offer ends {endsOn}.
              </p>
            )}
            <div className="rounded-[10px] bg-card/70 px-2.5 py-2">
              <p className="text-[11px] leading-[1.5] font-body text-foreground/80">
                Add it to your shelf so your next wash day logs correctly.
              </p>
              <button
                type="button"
                onClick={addToShelf}
                disabled={busy || onShelf}
                className="mt-1.5 min-h-[40px] w-full rounded-full border font-body font-semibold text-[12px] inline-flex items-center justify-center gap-1.5 disabled:opacity-70"
                style={{ borderColor: colours.accent, color: colours.accent }}
              >
                {busy ? (
                  <Loader2 className="size-3.5 animate-spin" />
                ) : onShelf ? (
                  <Check className="size-3.5" />
                ) : (
                  <Plus className="size-3.5" />
                )}
                {onShelf ? "On your shelf" : "Add to my shelf"}
              </button>
            </div>
          </div>
        )}
      </div>
    </section>
  );
};

export default SponsoredWashDayTipCard;
