// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-hair-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_hair_profile_default = defineTool({
  name: "get_hair_profile",
  title: "Get hair profile",
  description: "Return the signed-in STRAND user's profile: display name, birth year, country, heritage, and onboarding status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser(ctx);
      const { data, error } = await sb.from("profiles").select("display_name, birth_year, country, heritage, onboarding_completed_at").eq("user_id", ctx.getUserId()).maybeSingle();
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
        structuredContent: { profile: data }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-wash-days.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_wash_days_default = defineTool2({
  name: "list_wash_days",
  title: "List wash days",
  description: "Return the signed-in user's recent wash-day entries (date, scalp feel, breakage, stress level, duration, notes).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("How many entries to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser2(ctx);
      const { data, error } = await sb.from("wash_days").select(
        "id, wash_date, scalp_feel, breakage, stress_level, duration_min, style_after, hair_feel_note, ai_insight"
      ).eq("user_id", ctx.getUserId()).order("wash_date", { ascending: false }).limit(limit ?? 10);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
        structuredContent: { wash_days: data ?? [] }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-shelf-products.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_shelf_products_default = defineTool3({
  name: "list_shelf_products",
  title: "List shelf products",
  description: "Return products currently on the signed-in user's shelf, with brand, category, AI match score, rating, and use count.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser3(ctx);
      const { data, error } = await sb.from("user_products").select("id, name, brand, category, match_score, rating, use_count, last_used_at").eq("user_id", ctx.getUserId()).eq("on_shelf", true).order("last_used_at", { ascending: false, nullsFirst: false });
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
        structuredContent: { products: data ?? [] }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-goals.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_goals_default = defineTool4({
  name: "list_goals",
  title: "List goals",
  description: "Return the signed-in user's active hair goals with progress and target dates.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser4(ctx);
      const { data, error } = await sb.from("user_goals").select("id, title, kind, status, start_value, current_value, target_value, unit, target_date, target_text, notes").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
        structuredContent: { goals: data ?? [] }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-flagged-blood-markers.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_flagged_blood_markers_default = defineTool5({
  name: "list_flagged_blood_markers",
  title: "List flagged blood markers",
  description: "Return the signed-in user's blood markers that are outside the normal range (status = low or high). Encrypted values are omitted.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser5(ctx);
      const { data, error } = await sb.from("blood_results").select("marker, category, value, unit, status, updated_at").eq("user_id", ctx.getUserId()).in("status", ["low", "high"]).order("updated_at", { ascending: false });
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
        structuredContent: { flagged: data ?? [] }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-journal-entries.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_journal_entries_default = defineTool6({
  name: "list_journal_entries",
  title: "List style journal entries",
  description: "Return the signed-in user's recent style journal entries.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("How many entries to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser6(ctx);
      const { data, error } = await sb.from("journal_entries").select("id, entry_date, title, mood, note, products_used, photo_paths").eq("user_id", ctx.getUserId()).order("entry_date", { ascending: false }).limit(limit ?? 10);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
        structuredContent: { entries: data ?? [] }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/create-journal-entry.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser7(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_journal_entry_default = defineTool7({
  name: "create_journal_entry",
  title: "Create style journal entry",
  description: "Create a new style journal entry for the signed-in user.",
  inputSchema: {
    title: z3.string().trim().min(1).describe("Short title for the entry."),
    note: z3.string().optional().describe("Free-text note about the style, feel, or observations."),
    mood: z3.string().optional().describe("Optional mood tag."),
    entry_date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("ISO date (YYYY-MM-DD). Defaults to today.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, note, mood, entry_date }, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser7(ctx);
      const { data, error } = await sb.from("journal_entries").insert({
        user_id: ctx.getUserId(),
        title,
        note: note ?? null,
        mood: mood ?? null,
        entry_date: entry_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10)
      }).select("id, entry_date, title, mood, note").single();
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: `Created journal entry ${data.id}` }],
        structuredContent: { entry: data }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "wibimeglifveruvtvaxe";
var mcp_default = defineMcp({
  name: "strand-mcp",
  title: "STRAND",
  version: "0.1.0",
  instructions: "STRAND is a hair journal and clinical companion. Tools return data for the signed-in user only, scoped by row-level security. Use `get_hair_profile` and `list_flagged_blood_markers` for clinical context; `list_wash_days`, `list_shelf_products`, and `list_journal_entries` for care history; `list_goals` for active hair goals; and `create_journal_entry` to log a new style journal entry.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_hair_profile_default,
    list_wash_days_default,
    list_shelf_products_default,
    list_goals_default,
    list_flagged_blood_markers_default,
    list_journal_entries_default,
    create_journal_entry_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
