// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-hair-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_hair_profile_default = defineTool({
  name: "get_hair_profile",
  title: "Get hair profile",
  description: "Return the signed-in STRAND user's profile: display name, birth year, country, heritage, and onboarding status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser(ctx);
      const { data, error } = await sb.from("profiles").select("display_name, birth_year, country, heritage, onboarding_completed_at").eq("user_id", ctx.getUserId()).maybeSingle();
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
        structuredContent: { profile: data }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-wash-days.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_wash_days_default = defineTool2({
  name: "list_wash_days",
  title: "List wash days",
  description: "Return the signed-in user's recent wash-day entries (date, scalp feel, breakage, stress level, duration, notes).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("How many entries to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser2(ctx);
      const { data, error } = await sb.from("wash_days").select(
        "id, wash_date, scalp_feel, breakage, stress_level, duration_min, style_after, hair_feel_note, ai_insight"
      ).eq("user_id", ctx.getUserId()).order("wash_date", { ascending: false }).limit(limit ?? 10);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
        structuredContent: { wash_days: data ?? [] }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-shelf-products.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_shelf_products_default = defineTool3({
  name: "list_shelf_products",
  title: "List shelf products",
  description: "Return products currently on the signed-in user's shelf, with brand, category, AI match score, rating, and use count.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser3(ctx);
      const { data, error } = await sb.from("user_products").select("id, name, brand, category, match_score, rating, use_count, last_used_at").eq("user_id", ctx.getUserId()).eq("on_shelf", true).order("last_used_at", { ascending: false, nullsFirst: false });
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
        structuredContent: { products: data ?? [] }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-goals.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_goals_default = defineTool4({
  name: "list_goals",
  title: "List goals",
  description: "Return the signed-in user's active hair goals with progress and target dates.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser4(ctx);
      const { data, error } = await sb.from("user_goals").select("id, title, kind, status, start_value, current_value, target_value, unit, target_date, target_text, notes").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
        structuredContent: { goals: data ?? [] }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-flagged-blood-markers.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_flagged_blood_markers_default = defineTool5({
  name: "list_flagged_blood_markers",
  title: "List flagged blood markers",
  description: "Return the signed-in user's blood markers that are outside the normal range (status = low or high). Encrypted values are omitted.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser5(ctx);
      const { data, error } = await sb.from("blood_results").select("marker, category, value, unit, status, updated_at").eq("user_id", ctx.getUserId()).in("status", ["low", "high"]).order("updated_at", { ascending: false });
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
        structuredContent: { flagged: data ?? [] }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-journal-entries.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_journal_entries_default = defineTool6({
  name: "list_journal_entries",
  title: "List style journal entries",
  description: "Return the signed-in user's recent style journal entries.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("How many entries to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser6(ctx);
      const { data, error } = await sb.from("journal_entries").select("id, entry_date, title, mood, note, products_used, photo_paths").eq("user_id", ctx.getUserId()).order("entry_date", { ascending: false }).limit(limit ?? 10);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
        structuredContent: { entries: data ?? [] }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-appointments.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser7(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_appointments_default = defineTool7({
  name: "list_appointments",
  title: "List appointments",
  description: "Return the signed-in user's hair appointments (upcoming and past).",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("How many to return (default 20)."),
    status: z3.enum(["scheduled", "completed", "cancelled"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser7(ctx);
      let q = sb.from("appointments").select(
        "id, professional_name, professional_type, clinic_name, appointment_date, appointment_time, status, reason, notes, follow_up_needed"
      ).eq("user_id", ctx.getUserId()).order("appointment_date", { ascending: false }).limit(limit ?? 20);
      if (status) q = q.eq("status", status);
      const { data, error } = await q;
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
        structuredContent: { appointments: data ?? [] }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/create-journal-entry.ts
import { createClient as createClient8 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser8(ctx) {
  return createClient8(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_journal_entry_default = defineTool8({
  name: "create_journal_entry",
  title: "Create style journal entry",
  description: "Create a new style journal entry for the signed-in user.",
  inputSchema: {
    title: z4.string().trim().min(1).describe("Short title for the entry."),
    note: z4.string().optional().describe("Free-text note about the style, feel, or observations."),
    mood: z4.string().optional().describe("Optional mood tag."),
    entry_date: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("ISO date (YYYY-MM-DD). Defaults to today.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, note, mood, entry_date }, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser8(ctx);
      const { data, error } = await sb.from("journal_entries").insert({
        user_id: ctx.getUserId(),
        title,
        note: note ?? null,
        mood: mood ?? null,
        entry_date: entry_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10)
      }).select("id, entry_date, title, mood, note").single();
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: `Created journal entry ${data.id}` }],
        structuredContent: { entry: data }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/log-wash-day.ts
import { createClient as createClient9 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser9(ctx) {
  return createClient9(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var log_wash_day_default = defineTool9({
  name: "log_wash_day",
  title: "Log wash day",
  description: "Create a wash-day entry for the signed-in user. Use to record how a wash went: scalp feel, breakage, stress, duration, and any note. Product IDs must come from `list_shelf_products`.",
  inputSchema: {
    wash_date: z5.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("ISO date (YYYY-MM-DD). Defaults to today."),
    scalp_feel: z5.string().optional().describe("e.g. 'clean', 'itchy', 'oily'."),
    breakage: z5.string().optional().describe("e.g. 'none', 'light', 'moderate', 'heavy'."),
    stress_level: z5.number().int().min(1).max(10).optional().describe("1\u201310 stress this week."),
    duration_min: z5.number().int().min(1).max(720).optional().describe("Wash duration in minutes."),
    style_after: z5.string().optional().describe("Style worn after the wash."),
    hair_feel_note: z5.string().optional().describe("Free-text note on how the hair felt."),
    product_ids: z5.array(z5.string().uuid()).optional().describe("Array of user_products.id used during this wash.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser9(ctx);
      const { data, error } = await sb.from("wash_days").insert({
        user_id: ctx.getUserId(),
        wash_date: input.wash_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
        scalp_feel: input.scalp_feel ?? null,
        breakage: input.breakage ?? null,
        stress_level: input.stress_level ?? null,
        duration_min: input.duration_min ?? null,
        style_after: input.style_after ?? null,
        hair_feel_note: input.hair_feel_note ?? null,
        product_ids: input.product_ids ?? []
      }).select("id, wash_date").single();
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: `Logged wash day ${data.id} on ${data.wash_date}` }],
        structuredContent: { wash_day: data }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/add-product.ts
import { createClient as createClient10 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^3.25.76";
function supabaseForUser10(ctx) {
  return createClient10(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function keyOf(brand, name) {
  return `${(brand ?? "").trim().toLowerCase()}::${name.trim().toLowerCase()}`;
}
var add_product_default = defineTool10({
  name: "add_product",
  title: "Add product to shelf or wishlist",
  description: "Add a product for the signed-in user. Defaults to the shelf; set `destination` to 'wishlist' to save it for later. Ingredient analysis happens later inside the app.",
  inputSchema: {
    name: z6.string().trim().min(1).describe("Product name, e.g. 'Ultimate Moisture Hair Mask'."),
    brand: z6.string().trim().optional().describe("Brand name, e.g. 'Lola'."),
    category: z6.string().trim().optional().describe("Product category, e.g. 'mask', 'shampoo'."),
    source_url: z6.string().url().optional().describe("Product page URL, if known."),
    ingredients: z6.array(z6.string()).optional().describe("Ingredient list if already known."),
    destination: z6.enum(["shelf", "wishlist"]).optional().describe("Where to save it. Default 'shelf'.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser10(ctx);
      const toShelf = (input.destination ?? "shelf") === "shelf";
      const { data, error } = await sb.from("user_products").insert({
        user_id: ctx.getUserId(),
        name: input.name,
        brand: input.brand ?? null,
        category: input.category ?? null,
        source_url: input.source_url ?? null,
        ingredients: input.ingredients ?? [],
        product_key: keyOf(input.brand, input.name),
        on_shelf: toShelf,
        on_wishlist: !toShelf,
        added_to_shelf_at: toShelf ? (/* @__PURE__ */ new Date()).toISOString() : null
      }).select("id, name, brand, on_shelf, on_wishlist").single();
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [
          {
            type: "text",
            text: `Added ${data.brand ? data.brand + " " : ""}${data.name} to ${toShelf ? "shelf" : "wishlist"}.`
          }
        ],
        structuredContent: { product: data }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/set-product-status.ts
import { createClient as createClient11 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z7 } from "npm:zod@^3.25.76";
function supabaseForUser11(ctx) {
  return createClient11(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var set_product_status_default = defineTool11({
  name: "set_product_status",
  title: "Set product shelf status",
  description: "Move a product on/off the shelf, into/out of the wishlist, or favourite it. Pass only the flags you want to change. Use `list_shelf_products` first to get the product id.",
  inputSchema: {
    product_id: z7.string().uuid().describe("user_products.id for the product to update."),
    on_shelf: z7.boolean().optional(),
    on_wishlist: z7.boolean().optional(),
    on_favourite: z7.boolean().optional(),
    off_shelf_reason: z7.string().optional().describe("Reason when taking a product off the shelf.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser11(ctx);
      const patch = {};
      if (input.on_shelf !== void 0) {
        patch.on_shelf = input.on_shelf;
        if (!input.on_shelf) patch.previously_on_shelf = true;
        if (input.on_shelf) patch.added_to_shelf_at = (/* @__PURE__ */ new Date()).toISOString();
      }
      if (input.on_wishlist !== void 0) patch.on_wishlist = input.on_wishlist;
      if (input.on_favourite !== void 0) patch.on_favourite = input.on_favourite;
      if (input.off_shelf_reason !== void 0) patch.off_shelf_reason = input.off_shelf_reason;
      if (Object.keys(patch).length === 0)
        return { content: [{ type: "text", text: "No changes provided." }], isError: true };
      const { data, error } = await sb.from("user_products").update(patch).eq("id", input.product_id).eq("user_id", ctx.getUserId()).select("id, name, brand, on_shelf, on_wishlist, on_favourite").single();
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: `Updated ${data.name}.` }],
        structuredContent: { product: data }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/create-goal.ts
import { createClient as createClient12 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z8 } from "npm:zod@^3.25.76";
function supabaseForUser12(ctx) {
  return createClient12(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_goal_default = defineTool12({
  name: "create_goal",
  title: "Create hair goal",
  description: "Create a new hair goal for the signed-in user (e.g. length retention, moisture, breakage reduction). Length goals should route through the journal in-app, but any measurable target is fine.",
  inputSchema: {
    title: z8.string().trim().min(1).describe("Short goal title."),
    kind: z8.string().optional().describe("Category, e.g. 'length', 'moisture', 'breakage', 'scalp'."),
    start_value: z8.number().optional().describe("Baseline measurement."),
    current_value: z8.number().optional().describe("Current measurement."),
    target_value: z8.number().optional().describe("Target measurement."),
    unit: z8.string().optional().describe("Unit, e.g. 'inches', 'cm', '%'."),
    target_date: z8.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("ISO date (YYYY-MM-DD)."),
    target_text: z8.string().optional().describe("Free-text target when a number doesn't apply."),
    notes: z8.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser12(ctx);
      const { data, error } = await sb.from("user_goals").insert({
        user_id: ctx.getUserId(),
        title: input.title,
        kind: input.kind ?? "general",
        start_value: input.start_value ?? 0,
        current_value: input.current_value ?? input.start_value ?? 0,
        target_value: input.target_value ?? null,
        unit: input.unit ?? "",
        target_date: input.target_date ?? null,
        target_text: input.target_text ?? null,
        notes: input.notes ?? null
      }).select("id, title, kind, current_value, target_value, unit, target_date").single();
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: `Created goal ${data.id}: ${data.title}` }],
        structuredContent: { goal: data }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/update-goal-progress.ts
import { createClient as createClient13 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z9 } from "npm:zod@^3.25.76";
function supabaseForUser13(ctx) {
  return createClient13(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_goal_progress_default = defineTool13({
  name: "update_goal_progress",
  title: "Update goal progress",
  description: "Update `current_value`, `status`, or `notes` on a hair goal. Use `list_goals` first to get the goal id.",
  inputSchema: {
    goal_id: z9.string().uuid(),
    current_value: z9.number().optional(),
    status: z9.enum(["active", "paused", "achieved", "abandoned"]).optional(),
    notes: z9.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser13(ctx);
      const patch = {};
      if (input.current_value !== void 0) patch.current_value = input.current_value;
      if (input.status !== void 0) patch.status = input.status;
      if (input.notes !== void 0) patch.notes = input.notes;
      if (Object.keys(patch).length === 0)
        return { content: [{ type: "text", text: "No changes provided." }], isError: true };
      const { data, error } = await sb.from("user_goals").update(patch).eq("id", input.goal_id).eq("user_id", ctx.getUserId()).select("id, title, current_value, target_value, unit, status").single();
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: `Updated goal ${data.title}.` }],
        structuredContent: { goal: data }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/create-appointment.ts
import { createClient as createClient14 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z10 } from "npm:zod@^3.25.76";
function supabaseForUser14(ctx) {
  return createClient14(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_appointment_default = defineTool14({
  name: "create_appointment",
  title: "Create appointment",
  description: "Schedule or log an appointment with a hair professional (trichologist, dermatologist, curl specialist) for the signed-in user.",
  inputSchema: {
    professional_name: z10.string().trim().min(1),
    professional_type: z10.string().optional().describe("e.g. 'Trichologist', 'Dermatologist', 'Curl Specialist'."),
    clinic_name: z10.string().optional(),
    appointment_date: z10.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("ISO date (YYYY-MM-DD)."),
    appointment_time: z10.string().regex(/^\d{2}:\d{2}(:\d{2})?$/).optional().describe("24h time HH:MM."),
    reason: z10.string().optional(),
    notes: z10.string().optional(),
    status: z10.enum(["scheduled", "completed", "cancelled"]).optional(),
    follow_up_needed: z10.boolean().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser14(ctx);
      const { data, error } = await sb.from("appointments").insert({
        user_id: ctx.getUserId(),
        professional_name: input.professional_name,
        professional_type: input.professional_type ?? null,
        clinic_name: input.clinic_name ?? null,
        appointment_date: input.appointment_date,
        appointment_time: input.appointment_time ?? null,
        reason: input.reason ?? null,
        notes: input.notes ?? null,
        status: input.status ?? "scheduled",
        follow_up_needed: input.follow_up_needed ?? false
      }).select("id, professional_name, appointment_date, appointment_time, status").single();
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [
          { type: "text", text: `Created appointment ${data.id} with ${data.professional_name} on ${data.appointment_date}.` }
        ],
        structuredContent: { appointment: data }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/add-wishlist-item.ts
import { createClient as createClient15 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z11 } from "npm:zod@^3.25.76";
function supabaseForUser15(ctx) {
  return createClient15(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function keyOf2(brand, name) {
  return `${(brand ?? "").trim().toLowerCase()}::${name.trim().toLowerCase()}`;
}
var add_wishlist_item_default = defineTool15({
  name: "add_wishlist_item",
  title: "Add wishlist item",
  description: "Add a product to the signed-in user's wishlist (stored in `user_products` with on_wishlist=true). The `reason` is saved into `ai_summary` so the user sees why you recommended it.",
  inputSchema: {
    name: z11.string().trim().min(1).describe("Product name."),
    brand: z11.string().trim().optional().describe("Brand name."),
    category: z11.string().trim().optional().describe("Category, e.g. 'leave-in', 'oil', 'mask', 'supplement'."),
    reason: z11.string().trim().optional().describe("Why this is recommended for the user."),
    priority: z11.number().int().optional().describe("Optional priority ranking; stored as match_score.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser15(ctx);
      const product_key = keyOf2(input.brand, input.name);
      const { data: existing } = await sb.from("user_products").select("id, on_wishlist, on_shelf").eq("user_id", ctx.getUserId()).eq("product_key", product_key).maybeSingle();
      if (existing) {
        const { data: data2, error: error2 } = await sb.from("user_products").update({
          on_wishlist: true,
          ai_summary: input.reason ?? void 0,
          match_score: input.priority ?? void 0,
          category: input.category ?? void 0
        }).eq("id", existing.id).select("id, name, brand, on_wishlist, on_shelf").single();
        if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
        return {
          content: [{ type: "text", text: `Updated wishlist entry for ${data2.brand ? data2.brand + " " : ""}${data2.name}.` }],
          structuredContent: { item: data2 }
        };
      }
      const { data, error } = await sb.from("user_products").insert({
        user_id: ctx.getUserId(),
        name: input.name,
        brand: input.brand ?? null,
        category: input.category ?? null,
        product_key,
        on_wishlist: true,
        on_shelf: false,
        ai_summary: input.reason ?? null,
        match_score: input.priority ?? null
      }).select("id, name, brand, category, ai_summary, match_score, on_wishlist").single();
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: `Added ${data.brand ? data.brand + " " : ""}${data.name} to wishlist.` }],
        structuredContent: { item: data }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-wishlist-items.ts
import { createClient as createClient16 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z12 } from "npm:zod@^3.25.76";
function supabaseForUser16(ctx) {
  return createClient16(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_wishlist_items_default = defineTool16({
  name: "list_wishlist_items",
  title: "List wishlist items",
  description: "Return the signed-in user's active wishlist items (rows in `user_products` where on_wishlist=true).",
  inputSchema: {
    limit: z12.number().int().min(1).max(200).optional().describe("Max items to return (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      if (!ctx.isAuthenticated())
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      const sb = supabaseForUser16(ctx);
      const { data, error } = await sb.from("user_products").select("id, name, brand, category, ai_summary, match_score, created_at, on_shelf").eq("user_id", ctx.getUserId()).eq("on_wishlist", true).order("match_score", { ascending: true, nullsFirst: false }).order("created_at", { ascending: false }).limit(input.limit ?? 100);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      const items = (data ?? []).map((r) => ({
        id: r.id,
        name: r.name,
        brand: r.brand,
        category: r.category,
        reason: r.ai_summary,
        priority: r.match_score,
        moved_to_shelf: r.on_shelf,
        created_at: r.created_at
      }));
      return {
        content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
        structuredContent: { items }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Tool error: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "wibimeglifveruvtvaxe";
var mcp_default = defineMcp({
  name: "strand-mcp",
  title: "STRAND",
  version: "0.2.0",
  instructions: "STRAND is a hair journal and clinical companion. All tools are scoped to the signed-in user via row-level security. Read tools: `get_hair_profile`, `list_flagged_blood_markers` for clinical context; `list_shelf_products`, `list_wash_days`, `list_journal_entries`, `list_appointments` for care history; `list_goals` for active hair goals. Write tools (use to update the user's STRAND app): `log_wash_day` to record a wash session, `add_product` to add products to the shelf or wishlist, `set_product_status` to move products on/off the shelf or favourite them, `create_goal` and `update_goal_progress` to manage goals, `create_appointment` to schedule a hair appointment, `create_journal_entry` to log a style journal entry. Always cross-reference the user's hair profile, flagged blood markers, and recent wash history before recommending or writing changes.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    // Read
    get_hair_profile_default,
    list_wash_days_default,
    list_shelf_products_default,
    list_goals_default,
    list_flagged_blood_markers_default,
    list_journal_entries_default,
    list_appointments_default,
    // Write
    log_wash_day_default,
    add_product_default,
    set_product_status_default,
    create_goal_default,
    update_goal_progress_default,
    create_appointment_default,
    create_journal_entry_default,
    add_wishlist_item_default,
    list_wishlist_items_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
