ALTER TABLE public.user_products
  ADD COLUMN IF NOT EXISTS score_reasons jsonb NOT NULL DEFAULT '[]'::jsonb;

COMMENT ON COLUMN public.user_products.score_reasons IS
  'Structured match-score reasons: [{direction: plus|minus, factor, reason}] generated by the product analysis pipeline.';