import { useMemo, useState } from "react";
import { Loader2, Search, ShieldAlert } from "lucide-react";
import { toast } from "sonner";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import ScreenLayout from "@/components/ScreenLayout";
import TitleBar from "@/components/TitleBar";
import SurfaceCard from "@/components/SurfaceCard";
import SectionLabel from "@/components/SectionLabel";
import LoadingDot from "@/components/LoadingDot";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { useBloodMarkerReference } from "@/hooks/useBloodMarkerReference";
import type { HairLinkStatus } from "@/lib/bloodGuardrail";

/**
 * Blood marker reference — admin-only curation screen.
 *
 * NOTHING here is generated by AI or by the app. Every field is written by a
 * human from the manuscript or a citable source. A marker only unlocks
 * blood→hair reasoning in AI output once its status is "established" AND the
 * hair link wording is filled in; until then the guardrail suppresses any
 * blood-linked guidance for that marker.
 */

type Row = {
  id: string;
  marker: string;
  display_name: string;
  unit: string | null;
  ref_range_low: number | null;
  ref_range_high: number | null;
  plain_meaning: string | null;
  hair_link_status: HairLinkStatus;
  hair_link_summary: string | null;
  source_note: string | null;
};

const STATUSES: { value: HairLinkStatus; label: string; hint: string }[] = [
  { value: "none", label: "No hair link", hint: "AI may state the value only" },
  { value: "limited_evidence", label: "Limited evidence", hint: "AI may state the value only" },
  { value: "established", label: "Established", hint: "AI may use your wording below" },
];

const AdminBloodMarkers = () => {
  const { rows: refRows, loading } = useBloodMarkerReference();
  const qc = useQueryClient();
  const [query, setQuery] = useState("");
  const [openId, setOpenId] = useState<string | null>(null);
  const [draft, setDraft] = useState<Partial<Row>>({});

  const rows = useMemo(() => {
    const list = (refRows as unknown as Row[]) ?? [];
    const q = query.trim().toLowerCase();
    return q ? list.filter((r) => r.display_name.toLowerCase().includes(q)) : list;
  }, [refRows, query]);

  const save = useMutation({
    mutationFn: async (row: Partial<Row> & { id: string }) => {
      const { error } = await supabase
        .from("blood_marker_reference")
        .update({
          display_name: (row.display_name ?? "").trim(),
          unit: row.unit?.toString().trim() || null,
          ref_range_low: row.ref_range_low ?? null,
          ref_range_high: row.ref_range_high ?? null,
          plain_meaning: row.plain_meaning?.toString().trim() || null,
          hair_link_status: row.hair_link_status ?? "none",
          hair_link_summary: row.hair_link_summary?.toString().trim() || null,
          source_note: row.source_note?.toString().trim() || null,
        })
        .eq("id", row.id);
      if (error) throw error;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["blood-marker-reference"] });
      setOpenId(null);
      toast.success("Marker saved");
    },
    onError: (e) => toast.error(e instanceof Error ? e.message : "Could not save"),
  });

  const num = (v: string) => (v.trim() === "" ? null : Number(v));

  const submit = () => {
    if (!openId) return;
    if (draft.hair_link_status === "established" && !draft.hair_link_summary?.trim()) {
      toast.error("An established hair link needs the approved wording");
      return;
    }
    if (draft.hair_link_status === "established" && !draft.source_note?.trim()) {
      toast.error("An established hair link needs a source note");
      return;
    }
    save.mutate({ ...draft, id: openId });
  };

  if (loading) return <LoadingDot />;

  return (
    <ScreenLayout>
      <TitleBar title="Blood marker reference" />

      <div className="px-5 space-y-4 pb-10">
        <SurfaceCard className="p-4">
          <div className="flex gap-2">
            <ShieldAlert className="h-4 w-4 text-primary shrink-0 mt-0.5" />
            <p className="text-[12px] font-body text-muted-foreground leading-relaxed">
              Write every field yourself. The app never fills these in. While a marker
              is set to no hair link or limited evidence, AI guidance may only report
              the value against its range and point the member to a GP — it can never
              connect the marker to hair. Only "Established" plus wording you have
              written unlocks that connection, and the AI must use your wording.
            </p>
          </div>
        </SurfaceCard>

        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search markers"
            className="pl-9"
          />
        </div>

        <SectionLabel>{rows.length} markers</SectionLabel>

        <div className="space-y-2">
          {rows.map((r) => {
            const open = openId === r.id;
            return (
              <SurfaceCard key={r.id} className="p-4">
                <button
                  type="button"
                  className="w-full text-left"
                  onClick={() => {
                    setOpenId(open ? null : r.id);
                    setDraft(open ? {} : r);
                  }}
                >
                  <p className="font-display text-[15px]">{r.display_name}</p>
                  <p className="text-[11px] font-body text-muted-foreground">
                    {STATUSES.find((s) => s.value === r.hair_link_status)?.label}
                    {r.ref_range_low != null || r.ref_range_high != null
                      ? ` · ${r.ref_range_low ?? "–"}–${r.ref_range_high ?? "–"} ${r.unit ?? ""}`
                      : " · no range set"}
                  </p>
                </button>

                {open && (
                  <div className="mt-4 space-y-3">
                    <div>
                      <Label className="text-[11px]">Display name</Label>
                      <Input
                        value={draft.display_name ?? ""}
                        onChange={(e) => setDraft((d) => ({ ...d, display_name: e.target.value }))}
                      />
                    </div>
                    <div className="grid grid-cols-3 gap-2">
                      <div>
                        <Label className="text-[11px]">Unit</Label>
                        <Input
                          value={draft.unit ?? ""}
                          onChange={(e) => setDraft((d) => ({ ...d, unit: e.target.value }))}
                        />
                      </div>
                      <div>
                        <Label className="text-[11px]">Range low</Label>
                        <Input
                          inputMode="decimal"
                          value={draft.ref_range_low ?? ""}
                          onChange={(e) => setDraft((d) => ({ ...d, ref_range_low: num(e.target.value) }))}
                        />
                      </div>
                      <div>
                        <Label className="text-[11px]">Range high</Label>
                        <Input
                          inputMode="decimal"
                          value={draft.ref_range_high ?? ""}
                          onChange={(e) => setDraft((d) => ({ ...d, ref_range_high: num(e.target.value) }))}
                        />
                      </div>
                    </div>
                    <div>
                      <Label className="text-[11px]">Plain meaning</Label>
                      <Textarea
                        rows={2}
                        value={draft.plain_meaning ?? ""}
                        onChange={(e) => setDraft((d) => ({ ...d, plain_meaning: e.target.value }))}
                      />
                    </div>
                    <div>
                      <Label className="text-[11px]">Hair link status</Label>
                      <div className="flex flex-wrap gap-2 mt-1">
                        {STATUSES.map((s) => (
                          <button
                            key={s.value}
                            type="button"
                            onClick={() => setDraft((d) => ({ ...d, hair_link_status: s.value }))}
                            className={`rounded-pill px-3 py-1.5 text-[11px] font-body border ${
                              (draft.hair_link_status ?? "none") === s.value
                                ? "bg-primary text-primary-foreground border-primary"
                                : "border-border text-muted-foreground"
                            }`}
                          >
                            {s.label}
                          </button>
                        ))}
                      </div>
                      <p className="text-[10px] font-body text-muted-foreground mt-1">
                        {STATUSES.find((s) => s.value === (draft.hair_link_status ?? "none"))?.hint}
                      </p>
                    </div>
                    <div>
                      <Label className="text-[11px]">Hair link wording (used verbatim by AI)</Label>
                      <Textarea
                        rows={3}
                        value={draft.hair_link_summary ?? ""}
                        onChange={(e) => setDraft((d) => ({ ...d, hair_link_summary: e.target.value }))}
                      />
                    </div>
                    <div>
                      <Label className="text-[11px]">Source note</Label>
                      <Textarea
                        rows={2}
                        value={draft.source_note ?? ""}
                        onChange={(e) => setDraft((d) => ({ ...d, source_note: e.target.value }))}
                      />
                    </div>
                    <div className="flex gap-2">
                      <Button onClick={submit} disabled={save.isPending} className="rounded-pill flex-1">
                        {save.isPending && <Loader2 className="h-4 w-4 animate-spin mr-1" />}
                        Save
                      </Button>
                      <Button
                        variant="outline"
                        className="rounded-pill"
                        onClick={() => {
                          setOpenId(null);
                          setDraft({});
                        }}
                      >
                        Cancel
                      </Button>
                    </div>
                  </div>
                )}
              </SurfaceCard>
            );
          })}
        </div>
      </div>
    </ScreenLayout>
  );
};

export default AdminBloodMarkers;
